///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("fc087172-9d2d-4f87-89b4-fd8bf46c60bd", ModuleType.Recording, 1)]
    public partial class Recording2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RxAppRepository repository.
        /// </summary>
        public static RxAppRepository repo = RxAppRepository.Instance;

        static Recording2 instance = new Recording2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ImageBasedAutomation' at 14;4.", repo.ApplicationUnderTest.ImageBasedAutomationInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.ImageBasedAutomation.Click(new Location(ImageBasedAutomation_Screenshot1, "14;4", ImageBasedAutomation_Screenshot1_Options));
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ChkShowImage' at 4;5.", repo.ApplicationUnderTest.ChkShowImageInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.ChkShowImage.Click(new Location(ChkShowImage_Screenshot1, "4;5", ChkShowImage_Screenshot1_Options));
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TheCat' at 4;4.", repo.ApplicationUnderTest.TheCatInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.TheCat.Click(new Location(TheCat_Screenshot1, "4;4", TheCat_Screenshot1_Options));
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.TheCat' at 4;4.", repo.ApplicationUnderTest.TheCatInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.TheCat.MoveTo(new Location(TheCat_Screenshot1_2, "4;4", TheCat_Screenshot1_2_Options));
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.TheCat'.", repo.ApplicationUnderTest.TheCatInfo, new RecordItemIndex(4));
            Validate.Exists(repo.ApplicationUnderTest.TheCatInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        CompressedImage ImageBasedAutomation_Screenshot1
        { get { return repo.ApplicationUnderTest.ImageBasedAutomationInfo.GetScreenshot1(new Rectangle(8, 7, 23, 10)); } }

        Imaging.FindOptions ImageBasedAutomation_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage ChkShowImage_Screenshot1
        { get { return repo.ApplicationUnderTest.ChkShowImageInfo.GetScreenshot1(new Rectangle(4, 3, 8, 9)); } }

        Imaging.FindOptions ChkShowImage_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage TheCat_Screenshot1
        { get { return repo.ApplicationUnderTest.TheCatInfo.GetScreenshot1(new Rectangle(2, 2, 8, 8)); } }

        Imaging.FindOptions TheCat_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage TheCat_Screenshot1_2
        { get { return repo.ApplicationUnderTest.TheCatInfo.GetScreenshot1(new Rectangle(2, 2, 8, 8)); } }

        Imaging.FindOptions TheCat_Screenshot1_2_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
