///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxAppRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("789abdd5-3ab1-4f91-9bac-57b23f20fce6")]
    public partial class RxAppRepository : RepoGenBaseFolder
    {
        static RxAppRepository instance = new RxAppRepository();
        RxAppRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the RxAppRepository element repository.
        /// </summary>
        [RepositoryFolder("789abdd5-3ab1-4f91-9bac-57b23f20fce6")]
        public static RxAppRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxAppRepository() 
            : base("RxAppRepository", "/", null, 0, false, "789abdd5-3ab1-4f91-9bac-57b23f20fce6", ".\\RepositoryImages\\RxAppRepository789abdd5.rximgres")
        {
            _applicationundertest = new RxAppRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

        string _name = "";

        /// <summary>
        /// Gets or sets the value of variable name.
        /// </summary>
        [TestVariable("b6f3e0db-247c-4ef1-b667-ab4af01d1dc7")]
        public string name
        {
            get { return _name; }
            set { _name = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("789abdd5-3ab1-4f91-9bac-57b23f20fce6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("3802c67d-8984-4e7d-8459-836d46df639f")]
        public virtual RxAppRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class RxAppRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("3802c67d-8984-4e7d-8459-836d46df639f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lblwelcomemessageInfo;
            ImageBasedAutomationInfoClass _imagebasedautomationInfo;
            ChkShowImageInfoClass _chkshowimageInfo;
            TheCatInfoClass _thecatInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/form[@processname='RxDemoApp']", parentFolder, 30000, null, true, "3802c67d-8984-4e7d-8459-836d46df639f", "")
            {
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "?/?/tabpage[@controlname='RxTabIntroduction']/text[@controlname='lblWelcomeMessage']", 30000, null, "ad25e72b-b75b-4517-8156-41cfc563c874");
                _imagebasedautomationInfo = new ImageBasedAutomationInfoClass(this);
                _chkshowimageInfo = new ChkShowImageInfoClass(this);
                _thecatInfo = new TheCatInfoClass(this);
            }

            /// <summary>
            /// The ImageBasedAutomationInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("cb1d613a-8e27-4e9c-9951-a1f00c80fafd")]
            public class ImageBasedAutomationInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ImageBasedAutomationInfoClass class constructor.
                /// </summary>
                public ImageBasedAutomationInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ImageBasedAutomation", "?/?/tabpage[@accessiblename='Image-based automation']", 30000, null, "cb1d613a-8e27-4e9c-9951-a1f00c80fafd")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("7acedfd1-1400-4c6c-a1f2-3c733a41ce77")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("7acedfd1-1400-4c6c-a1f2-3c733a41ce77");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("7acedfd1-1400-4c6c-a1f2-3c733a41ce77")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("7acedfd1-1400-4c6c-a1f2-3c733a41ce77", cropRect);
                }
            }

            /// <summary>
            /// The ChkShowImageInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("adf5d1cc-72a5-4cfd-834e-b43f35dcdaf6")]
            public class ChkShowImageInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ChkShowImageInfoClass class constructor.
                /// </summary>
                public ChkShowImageInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ChkShowImage", "?/?/tabpage[@controlname='RxTabImageBased']/checkbox[@controlname='chkShowImage']", 30000, null, "adf5d1cc-72a5-4cfd-834e-b43f35dcdaf6")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("e546edfa-3499-4aaf-b192-ea16b4cc6741")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("e546edfa-3499-4aaf-b192-ea16b4cc6741");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e546edfa-3499-4aaf-b192-ea16b4cc6741")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e546edfa-3499-4aaf-b192-ea16b4cc6741", cropRect);
                }
            }

            /// <summary>
            /// The TheCatInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("068d7f40-3197-4063-bb56-263bc2c36700")]
            public class TheCatInfoClass : RepoItemInfo
            {
                /// <summary>
                /// TheCatInfoClass class constructor.
                /// </summary>
                public TheCatInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "TheCat", "?/?/tabpage[@controlname='RxTabImageBased']/picture[@controlname='TheCat']", 30000, null, "068d7f40-3197-4063-bb56-263bc2c36700")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("feabc28d-90a3-48ec-8691-7bdc667acd8b")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("feabc28d-90a3-48ec-8691-7bdc667acd8b");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("feabc28d-90a3-48ec-8691-7bdc667acd8b")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("feabc28d-90a3-48ec-8691-7bdc667acd8b", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3802c67d-8984-4e7d-8459-836d46df639f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3802c67d-8984-4e7d-8459-836d46df639f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("ad25e72b-b75b-4517-8156-41cfc563c874")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("ad25e72b-b75b-4517-8156-41cfc563c874")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item.
            /// </summary>
            [RepositoryItem("cb1d613a-8e27-4e9c-9951-a1f00c80fafd")]
            public virtual Ranorex.TabPage ImageBasedAutomation
            {
                get
                {
                    return _imagebasedautomationInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item info.
            /// </summary>
            [RepositoryItemInfo("cb1d613a-8e27-4e9c-9951-a1f00c80fafd")]
            public virtual ImageBasedAutomationInfoClass ImageBasedAutomationInfo
            {
                get
                {
                    return _imagebasedautomationInfo;
                }
            }

            /// <summary>
            /// The ChkShowImage item.
            /// </summary>
            [RepositoryItem("adf5d1cc-72a5-4cfd-834e-b43f35dcdaf6")]
            public virtual Ranorex.CheckBox ChkShowImage
            {
                get
                {
                    return _chkshowimageInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkShowImage item info.
            /// </summary>
            [RepositoryItemInfo("adf5d1cc-72a5-4cfd-834e-b43f35dcdaf6")]
            public virtual ChkShowImageInfoClass ChkShowImageInfo
            {
                get
                {
                    return _chkshowimageInfo;
                }
            }

            /// <summary>
            /// The TheCat item.
            /// </summary>
            [RepositoryItem("068d7f40-3197-4063-bb56-263bc2c36700")]
            public virtual Ranorex.Picture TheCat
            {
                get
                {
                    return _thecatInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The TheCat item info.
            /// </summary>
            [RepositoryItemInfo("068d7f40-3197-4063-bb56-263bc2c36700")]
            public virtual TheCatInfoClass TheCatInfo
            {
                get
                {
                    return _thecatInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}