///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDeskTopApp element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("6f986a80-3f5a-4781-b153-d1bbde5b2b4d")]
    public partial class RxDeskTopApp : RepoGenBaseFolder
    {
        static RxDeskTopApp instance = new RxDeskTopApp();
        RxDeskTopAppFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the RxDeskTopApp element repository.
        /// </summary>
        [RepositoryFolder("6f986a80-3f5a-4781-b153-d1bbde5b2b4d")]
        public static RxDeskTopApp Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDeskTopApp() 
            : base("RxDeskTopApp", "/", null, 0, false, "6f986a80-3f5a-4781-b153-d1bbde5b2b4d", ".\\RepositoryImages\\RxDeskTopApp6f986a80.rximgres")
        {
            _rxmainframe = new RxDeskTopAppFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6f986a80-3f5a-4781-b153-d1bbde5b2b4d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("19d26551-3813-4159-8e76-e22aa4291d39")]
        public virtual RxDeskTopAppFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class RxDeskTopAppFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("19d26551-3813-4159-8e76-e22aa4291d39")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RxDeskTopAppFolders.RxTabIntroductionFolder _rxtabintroduction;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "19d26551-3813-4159-8e76-e22aa4291d39", "")
            {
                _rxtabintroduction = new RxDeskTopAppFolders.RxTabIntroductionFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("19d26551-3813-4159-8e76-e22aa4291d39")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("19d26551-3813-4159-8e76-e22aa4291d39")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("6de2f80c-8f2c-4ec1-bcef-6348375ba8bf")]
            public virtual RxDeskTopAppFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("6de2f80c-8f2c-4ec1-bcef-6348375ba8bf")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enternametxboxInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _lblwelcomemessageInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "6de2f80c-8f2c-4ec1-bcef-6348375ba8bf", "")
            {
                _enternametxboxInfo = new RepoItemInfo(this, "EnterNameTxBox", "?/?/text[@accessiblename='Enter your name']", 30000, null, "782ab284-7e89-4932-a752-ed1edd43255f");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "button[@controlname='btnSubmitUserName']", 30000, null, "78d56ac4-5993-42d7-b62d-ea5d1643ac6b");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "text[@controlname='lblWelcomeMessage']", 30000, null, "a1947755-badf-4600-9c2c-79d13dd086de");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6de2f80c-8f2c-4ec1-bcef-6348375ba8bf")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6de2f80c-8f2c-4ec1-bcef-6348375ba8bf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterNameTxBox item.
            /// </summary>
            [RepositoryItem("782ab284-7e89-4932-a752-ed1edd43255f")]
            public virtual Ranorex.Text EnterNameTxBox
            {
                get
                {
                    return _enternametxboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterNameTxBox item info.
            /// </summary>
            [RepositoryItemInfo("782ab284-7e89-4932-a752-ed1edd43255f")]
            public virtual RepoItemInfo EnterNameTxBoxInfo
            {
                get
                {
                    return _enternametxboxInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("78d56ac4-5993-42d7-b62d-ea5d1643ac6b")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("78d56ac4-5993-42d7-b62d-ea5d1643ac6b")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("a1947755-badf-4600-9c2c-79d13dd086de")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("a1947755-badf-4600-9c2c-79d13dd086de")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}