///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WebAppTest.BookAFlight
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FlightConfirmationPage recording.
    /// </summary>
    [TestModule("19d9d972-f77f-4237-bdb1-e923f37bffe4", ModuleType.Recording, 1)]
    public partial class FlightConfirmationPage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::WebAppTest.WebAppTestRepository repository.
        /// </summary>
        public static global::WebAppTest.WebAppTestRepository repo = global::WebAppTest.WebAppTestRepository.Instance;

        static FlightConfirmationPage instance = new FlightConfirmationPage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FlightConfirmationPage()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FlightConfirmationPage Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Your \n        itinerary has been booked!') on item 'ApplicationUnderTest.SomeTableTag.YourItineraryHasBeenBooked'.", repo.ApplicationUnderTest.SomeTableTag.YourItineraryHasBeenBookedInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SomeTableTag.YourItineraryHasBeenBookedInfo, "InnerText", "Your \n        itinerary has been booked!");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
