///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WebAppTest.BookAFlight
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FlightFinderPage recording.
    /// </summary>
    [TestModule("a7a17988-1841-4ac9-b0e4-b65454e9b2cb", ModuleType.Recording, 1)]
    public partial class FlightFinderPage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::WebAppTest.WebAppTestRepository repository.
        /// </summary>
        public static global::WebAppTest.WebAppTestRepository repo = global::WebAppTest.WebAppTestRepository.Instance;

        static FlightFinderPage instance = new FlightFinderPage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FlightFinderPage()
        {
            NoOfPassangers = "3";
            from = "New York";
            to = "Frankfurt";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FlightFinderPage Instance
        {
            get { return instance; }
        }

#region Variables

        string _NoOfPassangers;

        /// <summary>
        /// Gets or sets the value of variable NoOfPassangers.
        /// </summary>
        [TestVariable("05344f5a-4165-4fdf-932e-30840c7c3369")]
        public string NoOfPassangers
        {
            get { return _NoOfPassangers; }
            set { _NoOfPassangers = value; }
        }

        string _from;

        /// <summary>
        /// Gets or sets the value of variable from.
        /// </summary>
        [TestVariable("70a19e4c-9226-44ba-bc0d-c3741d77c825")]
        public string from
        {
            get { return _from; }
            set { _from = value; }
        }

        string _to;

        /// <summary>
        /// Gets or sets the value of variable to.
        /// </summary>
        [TestVariable("9e2b9e8b-dc50-440a-81e6-34ed434b34ff")]
        public string to
        {
            get { return _to; }
            set { _to = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.TripType' at 9;5.", repo.ApplicationUnderTest.SomeTableTag.TripTypeInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.SomeTableTag.TripType.Click("9;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.TripType1' at 6;4.", repo.ApplicationUnderTest.SomeTableTag.TripType1Info, new RecordItemIndex(1));
            repo.ApplicationUnderTest.SomeTableTag.TripType1.Click("6;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$NoOfPassangers' on item 'ApplicationUnderTest.SomeTableTag.PassCount'.", repo.ApplicationUnderTest.SomeTableTag.PassCountInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.SomeTableTag.PassCount.Element.SetAttributeValue("TagValue", NoOfPassangers);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$from' on item 'ApplicationUnderTest.SomeTableTag.FromPort'.", repo.ApplicationUnderTest.SomeTableTag.FromPortInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.SomeTableTag.FromPort.Element.SetAttributeValue("TagValue", from);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '12' on item 'ApplicationUnderTest.SomeTableTag.FromMonth'.", repo.ApplicationUnderTest.SomeTableTag.FromMonthInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.SomeTableTag.FromMonth.Element.SetAttributeValue("TagValue", "12");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '20' on item 'ApplicationUnderTest.SomeTableTag.FromDay'.", repo.ApplicationUnderTest.SomeTableTag.FromDayInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.SomeTableTag.FromDay.Element.SetAttributeValue("TagValue", "20");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$to' on item 'ApplicationUnderTest.SomeTableTag.ToPort'.", repo.ApplicationUnderTest.SomeTableTag.ToPortInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.SomeTableTag.ToPort.Element.SetAttributeValue("TagValue", to);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '12' on item 'ApplicationUnderTest.SomeTableTag.ToMonth'.", repo.ApplicationUnderTest.SomeTableTag.ToMonthInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.SomeTableTag.ToMonth.Element.SetAttributeValue("TagValue", "12");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '21' on item 'ApplicationUnderTest.SomeTableTag.ToDay'.", repo.ApplicationUnderTest.SomeTableTag.ToDayInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.SomeTableTag.ToDay.Element.SetAttributeValue("TagValue", "21");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.ServClass' at 6;8.", repo.ApplicationUnderTest.SomeTableTag.ServClassInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.SomeTableTag.ServClass.Click("6;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Blue Skies Airlines' on item 'ApplicationUnderTest.SomeTableTag.Airline'.", repo.ApplicationUnderTest.SomeTableTag.AirlineInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.SomeTableTag.Airline.Element.SetAttributeValue("TagValue", "Blue Skies Airlines");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.FindFlights' at 61;13.", repo.ApplicationUnderTest.SomeTableTag.FindFlightsInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.SomeTableTag.FindFlights.Click("61;13");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
