///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WebAppTest.BookAFlight
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelectAFlight recording.
    /// </summary>
    [TestModule("df81f0d0-57b2-479c-8052-6e54f8adc6e3", ModuleType.Recording, 1)]
    public partial class SelectAFlight : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::WebAppTest.WebAppTestRepository repository.
        /// </summary>
        public static global::WebAppTest.WebAppTestRepository repo = global::WebAppTest.WebAppTestRepository.Instance;

        static SelectAFlight instance = new SelectAFlight();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectAFlight()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectAFlight Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.OutFlight' at 8;7.", repo.ApplicationUnderTest.SomeTableTag.OutFlightInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.SomeTableTag.OutFlight.Click("8;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.InFlight' at 6;8.", repo.ApplicationUnderTest.SomeTableTag.InFlightInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.SomeTableTag.InFlight.Click("6;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest' at 1360;313.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Self.MoveTo("1360;313");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.ReserveFlights' at 60;12.", repo.ApplicationUnderTest.SomeTableTag.ReserveFlightsInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.SomeTableTag.ReserveFlights.Click("60;12");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
