///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WebAppTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WebAppTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("47e7d8aa-0a18-472d-9bc4-2ef259037955")]
    public partial class WebAppTestRepository : RepoGenBaseFolder
    {
        static WebAppTestRepository instance = new WebAppTestRepository();
        WebAppTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        WebAppTestRepositoryFolders.SelectboxAppFolder _selectbox;
        WebAppTestRepositoryFolders.FindAFlightMercuryToursInternetAppFolder _findaflightmercurytoursinternet;

        /// <summary>
        /// Gets the singleton class instance representing the WebAppTestRepository element repository.
        /// </summary>
        [RepositoryFolder("47e7d8aa-0a18-472d-9bc4-2ef259037955")]
        public static WebAppTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WebAppTestRepository() 
            : base("WebAppTestRepository", "/", null, 0, false, "47e7d8aa-0a18-472d-9bc4-2ef259037955", ".\\RepositoryImages\\WebAppTestRepository47e7d8aa.rximgres")
        {
            _applicationundertest = new WebAppTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _selectbox = new WebAppTestRepositoryFolders.SelectboxAppFolder(this);
            _findaflightmercurytoursinternet = new WebAppTestRepositoryFolders.FindAFlightMercuryToursInternetAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("47e7d8aa-0a18-472d-9bc4-2ef259037955")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("bdabeae9-6a45-4d8e-83e5-52b6e67ea97a")]
        public virtual WebAppTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Selectbox folder.
        /// </summary>
        [RepositoryFolder("a8758683-e4f6-4e37-b887-b44b5493d8a1")]
        public virtual WebAppTestRepositoryFolders.SelectboxAppFolder Selectbox
        {
            get { return _selectbox; }
        }

        /// <summary>
        /// The FindAFlightMercuryToursInternet folder.
        /// </summary>
        [RepositoryFolder("80de4d1e-490c-4299-8eb7-6e6e6dcabd5b")]
        public virtual WebAppTestRepositoryFolders.FindAFlightMercuryToursInternetAppFolder FindAFlightMercuryToursInternet
        {
            get { return _findaflightmercurytoursinternet; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class WebAppTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("bdabeae9-6a45-4d8e-83e5-52b6e67ea97a")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            WebAppTestRepositoryFolders.SomeTableTagFolder _sometabletag;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _flightsInfo;
            RepoItemInfo _somedivtagInfo;
            RepoItemInfo _somebodytagInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='newtours.demoaut.com']", parentFolder, 30000, null, true, "bdabeae9-6a45-4d8e-83e5-52b6e67ea97a", "")
            {
                _sometabletag = new WebAppTestRepositoryFolders.SomeTableTagFolder(this);
                _usernameInfo = new RepoItemInfo(this, "UserName", ".//input[#'userName']", 30000, null, "0325865f-21e2-4902-8bad-fc64ad5a8dcf");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", 30000, null, "2665351c-7c30-4a1e-b442-97f63ca87aec");
                _flightsInfo = new RepoItemInfo(this, "Flights", "body/?/?/table/?/?/tr/td[1]/table/tbody//table//td/table/tbody/tr[2]/td[2]/a[@innertext='Flights']", 30000, null, "f94157a3-05e4-4a76-b509-5acf0387ad4a");
                _somedivtagInfo = new RepoItemInfo(this, "SomeDivTag", "?/?/div", 30000, null, "039b71f0-a451-4795-a5e9-9e509f20a634");
                _somebodytagInfo = new RepoItemInfo(this, "SomeBodyTag", "body", 30000, null, "1090de88-6783-4cb5-bc1d-5b408d4ef8ed");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bdabeae9-6a45-4d8e-83e5-52b6e67ea97a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bdabeae9-6a45-4d8e-83e5-52b6e67ea97a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("0325865f-21e2-4902-8bad-fc64ad5a8dcf")]
            public virtual Ranorex.InputTag UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("0325865f-21e2-4902-8bad-fc64ad5a8dcf")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("2665351c-7c30-4a1e-b442-97f63ca87aec")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("2665351c-7c30-4a1e-b442-97f63ca87aec")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Flights item.
            /// </summary>
            [RepositoryItem("f94157a3-05e4-4a76-b509-5acf0387ad4a")]
            public virtual Ranorex.ATag Flights
            {
                get
                {
                    return _flightsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Flights item info.
            /// </summary>
            [RepositoryItemInfo("f94157a3-05e4-4a76-b509-5acf0387ad4a")]
            public virtual RepoItemInfo FlightsInfo
            {
                get
                {
                    return _flightsInfo;
                }
            }

            /// <summary>
            /// The SomeDivTag item.
            /// </summary>
            [RepositoryItem("039b71f0-a451-4795-a5e9-9e509f20a634")]
            public virtual Ranorex.DivTag SomeDivTag
            {
                get
                {
                    return _somedivtagInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeDivTag item info.
            /// </summary>
            [RepositoryItemInfo("039b71f0-a451-4795-a5e9-9e509f20a634")]
            public virtual RepoItemInfo SomeDivTagInfo
            {
                get
                {
                    return _somedivtagInfo;
                }
            }

            /// <summary>
            /// The SomeBodyTag item.
            /// </summary>
            [RepositoryItem("1090de88-6783-4cb5-bc1d-5b408d4ef8ed")]
            public virtual Ranorex.BodyTag SomeBodyTag
            {
                get
                {
                    return _somebodytagInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The SomeBodyTag item info.
            /// </summary>
            [RepositoryItemInfo("1090de88-6783-4cb5-bc1d-5b408d4ef8ed")]
            public virtual RepoItemInfo SomeBodyTagInfo
            {
                get
                {
                    return _somebodytagInfo;
                }
            }

            /// <summary>
            /// The SomeTableTag folder.
            /// </summary>
            [RepositoryFolder("4058afe2-19c7-4e03-8445-a5f827a97980")]
            public virtual WebAppTestRepositoryFolders.SomeTableTagFolder SomeTableTag
            {
                get { return _sometabletag; }
            }
        }

        /// <summary>
        /// The SomeTableTagFolder folder.
        /// </summary>
        [RepositoryFolder("4058afe2-19c7-4e03-8445-a5f827a97980")]
        public partial class SomeTableTagFolder : RepoGenBaseFolder
        {
            RepoItemInfo _registerInfo;
            RepoItemInfo _stateInfo;
            RepoItemInfo _postalcodeInfo;
            RepoItemInfo _countryInfo;
            RepoItemInfo _confirmpasswordInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _phoneInfo;
            RepoItemInfo _address1Info;
            RepoItemInfo _address2Info;
            RepoItemInfo _cityInfo;
            RepoItemInfo _register1Info;
            RepoItemInfo _btagdearshreyatasugandhiInfo;
            RepoItemInfo _triptypeInfo;
            RepoItemInfo _triptype1Info;
            RepoItemInfo _passcountInfo;
            RepoItemInfo _fromportInfo;
            RepoItemInfo _frommonthInfo;
            RepoItemInfo _fromdayInfo;
            RepoItemInfo _toportInfo;
            RepoItemInfo _tomonthInfo;
            RepoItemInfo _todayInfo;
            RepoItemInfo _servclassInfo;
            RepoItemInfo _airlineInfo;
            RepoItemInfo _findflightsInfo;
            RepoItemInfo _outflightInfo;
            RepoItemInfo _inflightInfo;
            RepoItemInfo _reserveflightsInfo;
            RepoItemInfo _passfirst0Info;
            RepoItemInfo _passlast0Info;
            RepoItemInfo _pass0mealInfo;
            RepoItemInfo _passfirst1Info;
            RepoItemInfo _passlast1Info;
            RepoItemInfo _pass1mealInfo;
            RepoItemInfo _passfirst2Info;
            RepoItemInfo _passlast2Info;
            RepoItemInfo _pass2mealInfo;
            RepoItemInfo _creditnumberInfo;
            RepoItemInfo _buyflightsInfo;
            RepoItemInfo _youritineraryhasbeenbookedInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginInfo;
            RepoItemInfo _httpnewtoursdemoautcomimagesmastsInfo;

            /// <summary>
            /// Creates a new SomeTableTag  folder.
            /// </summary>
            public SomeTableTagFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeTableTag", "body/?/?/table/?/?/tr/td[2]/table", parentFolder, 30000, null, false, "4058afe2-19c7-4e03-8445-a5f827a97980", "")
            {
                _registerInfo = new RepoItemInfo(this, "REGISTER", "tbody/tr[2]/?/?/table/?/?/tr/td[2]/a[@innertext='REGISTER']", 30000, null, "1a29baf5-b1e9-4d69-828d-7c223bf0dbf2");
                _stateInfo = new RepoItemInfo(this, "State", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@action='mercurycreate_account.php']/table/tbody/tr[10]/?/?/input[@name='state']", 30000, null, "3f76f35b-ac2f-473b-b81b-0b53a33b8b39");
                _postalcodeInfo = new RepoItemInfo(this, "PostalCode", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@action='mercurycreate_account.php']/table/tbody/tr[11]/?/?/input[@name='postalCode']", 30000, null, "197b8b33-50c4-42d3-b4d7-dc7d89d44453");
                _countryInfo = new RepoItemInfo(this, "Country", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@action='mercurycreate_account.php']/table/tbody/tr[12]/?/?/select[@name='country']", 30000, null, "7b6bc657-1e22-452c-8d96-c5cb4dee1d77");
                _confirmpasswordInfo = new RepoItemInfo(this, "ConfirmPassword", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@action='mercurycreate_account.php']/table/tbody/tr[16]/?/?/input[@name='confirmPassword']", 30000, null, "830ca2b9-c4c0-4b9b-a74f-a48bd532c75c");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@action='mercurycreate_account.php']/table/tbody/tr[2]/?/?/input[@name='firstName']", 30000, null, "2f51d943-9af1-410b-8045-7b8abeb254b9");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@action='mercurycreate_account.php']/table/tbody/tr[3]/?/?/input[@name='lastName']", 30000, null, "1323c453-a240-408e-8fc2-0234fa98d4f6");
                _phoneInfo = new RepoItemInfo(this, "Phone", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@action='mercurycreate_account.php']/table/tbody/tr[4]/?/?/input[@name='phone']", 30000, null, "d54cb936-ecb4-42ff-a7f2-92def43bcd37");
                _address1Info = new RepoItemInfo(this, "Address1", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@action='mercurycreate_account.php']/table/tbody/tr[7]/?/?/input[@name='address1']", 30000, null, "edc29f06-3826-4c3e-b1ab-4e7a39f4b0e8");
                _address2Info = new RepoItemInfo(this, "Address2", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@action='mercurycreate_account.php']/table/tbody/tr[8]/?/?/input[@name='address2']", 30000, null, "57000dea-7599-4f06-be09-a5541de2ef23");
                _cityInfo = new RepoItemInfo(this, "City", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@action='mercurycreate_account.php']/table/tbody/tr[9]/?/?/input[@name='city']", 30000, null, "8057cedb-5b61-40a2-ac92-d5645721ca67");
                _register1Info = new RepoItemInfo(this, "Register1", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@action='mercurycreate_account.php']/table/tbody/tr[18]/?/?/input[@name='register']", 30000, null, "b5f06ee8-ac11-4330-b54e-6e457d383b4e");
                _btagdearshreyatasugandhiInfo = new RepoItemInfo(this, "BTagDearShreyataSugandhi", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[3]/td/p[1]/?/?/b[@innertext=' Dear Shreyata Sugandhi,']", 30000, null, "8c93d372-8c1d-4137-b4fa-9a11d4f4c205");
                _triptypeInfo = new RepoItemInfo(this, "TripType", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='findflight']/table/tbody/tr[2]/td[2]/?/?/font[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ Round\\ Trip']/input[@type='radio' and @value='roundtrip']", 30000, null, "d8ba1f43-f041-4d2a-9344-ce505f9def37");
                _triptype1Info = new RepoItemInfo(this, "TripType1", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='findflight']/table/tbody/tr[2]/td[2]/?/?/font[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ Round\\ Trip']/input[@type='radio' and @value='oneway']", 30000, null, "cb4a294d-5af2-42a8-a215-be2464843a04");
                _passcountInfo = new RepoItemInfo(this, "PassCount", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='findflight']/table/tbody/tr[3]/td[2]/?/?/select[@name='passCount']", 30000, null, "1be40ccf-9106-47e0-8c4f-a88729aeb82b");
                _fromportInfo = new RepoItemInfo(this, "FromPort", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='findflight']/table/tbody/tr[4]/?/?/select[@name='fromPort']", 30000, null, "d6cacf91-b0f2-4ba0-a54d-8dd4a6c4911d");
                _frommonthInfo = new RepoItemInfo(this, "FromMonth", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='findflight']/table/tbody/tr[5]/?/?/select[@name='fromMonth']", 30000, null, "df5dfc32-d492-4000-893d-b53874334b8f");
                _fromdayInfo = new RepoItemInfo(this, "FromDay", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='findflight']/table/tbody/tr[5]/?/?/select[@name='fromDay']", 30000, null, "47c118ae-a58b-4cfa-8b2c-ea8b9cc647fc");
                _toportInfo = new RepoItemInfo(this, "ToPort", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='findflight']/table/tbody/tr[6]/?/?/select[@name='toPort']", 30000, null, "bd05b57c-438d-4672-bab8-784c7ad568fb");
                _tomonthInfo = new RepoItemInfo(this, "ToMonth", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='findflight']/table/tbody/tr[7]/?/?/select[@name='toMonth']", 30000, null, "aed7bfc5-c1dd-43d8-8c81-3cb2a233dff5");
                _todayInfo = new RepoItemInfo(this, "ToDay", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='findflight']/table/tbody/tr[7]/?/?/select[@name='toDay']", 30000, null, "556bf797-0aba-46de-8c45-9d5b9883aca1");
                _servclassInfo = new RepoItemInfo(this, "ServClass", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='findflight']/table/tbody/tr[9]/td[2]/?/?/font[@innertext~'^Economy\\ class\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']/input[@type='radio' and @value='First']", 30000, null, "b48688bc-9871-443c-b6a5-b806f5293c3b");
                _airlineInfo = new RepoItemInfo(this, "Airline", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='findflight']/table/tbody/tr[10]/?/?/select[@name='airline']", 30000, null, "5b760db6-40b5-4d99-8754-041ed2c4ba4c");
                _findflightsInfo = new RepoItemInfo(this, "FindFlights", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='findflight']/table/tbody/tr[14]/?/?/input[@name='findFlights']", 30000, null, "6026656f-fe3b-485b-8f0d-6e6b34a6b11b");
                _outflightInfo = new RepoItemInfo(this, "OutFlight", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='results']/table[1]/tbody/tr[5]/td[1]/input[@name='outFlight']", 30000, null, "d60828d3-301e-40a6-9d99-51b88deae4c9");
                _inflightInfo = new RepoItemInfo(this, "InFlight", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='results']/table[2]/tbody/tr[5]/td[1]/input[@name='inFlight']", 30000, null, "4bea2c69-8bc9-42b8-9290-53945d909217");
                _reserveflightsInfo = new RepoItemInfo(this, "ReserveFlights", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='results']/p/input[@name='reserveFlights']", 30000, null, "11cad15f-c3e0-4fcf-8abe-5dabdcee54d1");
                _passfirst0Info = new RepoItemInfo(this, "PassFirst0", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[4]/?/?/table/tbody/tr[2]/td[1]/input[@name='passFirst0']", 30000, null, "cff623a5-28b6-4f80-8e25-08a0373bd1b8");
                _passlast0Info = new RepoItemInfo(this, "PassLast0", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[4]/?/?/table/tbody/tr[2]/td[2]/input[@name='passLast0']", 30000, null, "90df8166-67ff-4dc7-a071-9e612d7b72b3");
                _pass0mealInfo = new RepoItemInfo(this, "Pass0Meal", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[4]/?/?/table/tbody/tr[2]/td[3]/select[@name='pass.0.meal']", 30000, null, "71bdde25-ef8b-4f68-aad3-e4078c84b576");
                _passfirst1Info = new RepoItemInfo(this, "PassFirst1", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[5]/?/?/table/tbody/tr[2]/td[1]/input[@name='passFirst1']", 30000, null, "dea3851b-c9e3-4997-8660-4a961a47ff25");
                _passlast1Info = new RepoItemInfo(this, "PassLast1", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[5]/?/?/table/tbody/tr[2]/td[2]/input[@name='passLast1']", 30000, null, "7894f957-e52c-466a-9a5e-329c914e61c0");
                _pass1mealInfo = new RepoItemInfo(this, "Pass1Meal", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[5]/?/?/table/tbody/tr[2]/td[3]/select[@name='pass.1.meal']", 30000, null, "1a18057a-1946-4d66-80e7-72ca69f849d0");
                _passfirst2Info = new RepoItemInfo(this, "PassFirst2", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[6]/?/?/table/tbody/tr[2]/td[1]/input[@name='passFirst2']", 30000, null, "b56f2968-a9c7-44fe-9e1f-a73c7cbe0d79");
                _passlast2Info = new RepoItemInfo(this, "PassLast2", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[6]/?/?/table/tbody/tr[2]/td[2]/input[@name='passLast2']", 30000, null, "f51c3172-72a2-4468-8b79-907490a60b4b");
                _pass2mealInfo = new RepoItemInfo(this, "Pass2Meal", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[6]/?/?/table/tbody/tr[2]/td[3]/select[@name='pass.2.meal']", 30000, null, "461baf8c-48df-4d0d-ba30-f2919be1fcac");
                _creditnumberInfo = new RepoItemInfo(this, "Creditnumber", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[8]/?/?/table/tbody/tr[2]/td[2]/input[@name='creditnumber']", 30000, null, "2b1d4cdc-854c-4f92-953f-fe74eddbfb2b");
                _buyflightsInfo = new RepoItemInfo(this, "BuyFlights", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[25]/?/?/input[@name='buyFlights']", 30000, null, "2a0aa8ac-27ff-427c-b01a-abb6bf894b1f");
                _youritineraryhasbeenbookedInfo = new RepoItemInfo(this, "YourItineraryHasBeenBooked", "tbody/tr[4]/?/?/table/tbody/tr[1]/?/?/table/tbody/tr[3]//font[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ Please\\ print\\ a\\ c']/b/font[@innertext~'^Your\\ \\ \\ \\ \\ \\ \\ \\ \\ itinerary\\ h']", 30000, null, "7fb24d00-2a0f-46f3-9076-6090b5a56329");
                _usernameInfo = new RepoItemInfo(this, "UserName", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[2]/td[3]/form[@name='home']/table/tbody/tr[4]/?/?/table/tbody/tr[2]/?/?/input[@name='userName']", 30000, null, "30415600-3f5f-4e97-aba2-9e3aba19bc98");
                _passwordInfo = new RepoItemInfo(this, "Password", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[2]/td[3]/form[@name='home']/table/tbody/tr[4]/?/?/table/tbody/tr[3]/?/?/input[@name='password']", 30000, null, "473fc299-e75d-4195-9473-a10812cc6390");
                _loginInfo = new RepoItemInfo(this, "Login", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[2]/td[3]/form[@name='home']/table/tbody/tr[4]/?/?/table/tbody/tr[4]//input[@name='login']", 30000, null, "96f482fc-bbfe-4b4f-bc33-fda34d0e1f9d");
                _httpnewtoursdemoautcomimagesmastsInfo = new RepoItemInfo(this, "HttpNewtoursDemoautComImagesMasts", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[1]/?/?/img[@src='http://newtours.demoaut.com/images/masts/mast_flightfinder.gif']", 30000, null, "8f0192e4-22fb-4cab-a19e-5a642dbadf0a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4058afe2-19c7-4e03-8445-a5f827a97980")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4058afe2-19c7-4e03-8445-a5f827a97980")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The REGISTER item.
            /// </summary>
            [RepositoryItem("1a29baf5-b1e9-4d69-828d-7c223bf0dbf2")]
            public virtual Ranorex.ATag REGISTER
            {
                get
                {
                    return _registerInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The REGISTER item info.
            /// </summary>
            [RepositoryItemInfo("1a29baf5-b1e9-4d69-828d-7c223bf0dbf2")]
            public virtual RepoItemInfo REGISTERInfo
            {
                get
                {
                    return _registerInfo;
                }
            }

            /// <summary>
            /// The State item.
            /// </summary>
            [RepositoryItem("3f76f35b-ac2f-473b-b81b-0b53a33b8b39")]
            public virtual Ranorex.InputTag State
            {
                get
                {
                    return _stateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The State item info.
            /// </summary>
            [RepositoryItemInfo("3f76f35b-ac2f-473b-b81b-0b53a33b8b39")]
            public virtual RepoItemInfo StateInfo
            {
                get
                {
                    return _stateInfo;
                }
            }

            /// <summary>
            /// The PostalCode item.
            /// </summary>
            [RepositoryItem("197b8b33-50c4-42d3-b4d7-dc7d89d44453")]
            public virtual Ranorex.InputTag PostalCode
            {
                get
                {
                    return _postalcodeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PostalCode item info.
            /// </summary>
            [RepositoryItemInfo("197b8b33-50c4-42d3-b4d7-dc7d89d44453")]
            public virtual RepoItemInfo PostalCodeInfo
            {
                get
                {
                    return _postalcodeInfo;
                }
            }

            /// <summary>
            /// The Country item.
            /// </summary>
            [RepositoryItem("7b6bc657-1e22-452c-8d96-c5cb4dee1d77")]
            public virtual Ranorex.SelectTag Country
            {
                get
                {
                    return _countryInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Country item info.
            /// </summary>
            [RepositoryItemInfo("7b6bc657-1e22-452c-8d96-c5cb4dee1d77")]
            public virtual RepoItemInfo CountryInfo
            {
                get
                {
                    return _countryInfo;
                }
            }

            /// <summary>
            /// The ConfirmPassword item.
            /// </summary>
            [RepositoryItem("830ca2b9-c4c0-4b9b-a74f-a48bd532c75c")]
            public virtual Ranorex.InputTag ConfirmPassword
            {
                get
                {
                    return _confirmpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ConfirmPassword item info.
            /// </summary>
            [RepositoryItemInfo("830ca2b9-c4c0-4b9b-a74f-a48bd532c75c")]
            public virtual RepoItemInfo ConfirmPasswordInfo
            {
                get
                {
                    return _confirmpasswordInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("2f51d943-9af1-410b-8045-7b8abeb254b9")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("2f51d943-9af1-410b-8045-7b8abeb254b9")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("1323c453-a240-408e-8fc2-0234fa98d4f6")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("1323c453-a240-408e-8fc2-0234fa98d4f6")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Phone item.
            /// </summary>
            [RepositoryItem("d54cb936-ecb4-42ff-a7f2-92def43bcd37")]
            public virtual Ranorex.InputTag Phone
            {
                get
                {
                    return _phoneInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Phone item info.
            /// </summary>
            [RepositoryItemInfo("d54cb936-ecb4-42ff-a7f2-92def43bcd37")]
            public virtual RepoItemInfo PhoneInfo
            {
                get
                {
                    return _phoneInfo;
                }
            }

            /// <summary>
            /// The Address1 item.
            /// </summary>
            [RepositoryItem("edc29f06-3826-4c3e-b1ab-4e7a39f4b0e8")]
            public virtual Ranorex.InputTag Address1
            {
                get
                {
                    return _address1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Address1 item info.
            /// </summary>
            [RepositoryItemInfo("edc29f06-3826-4c3e-b1ab-4e7a39f4b0e8")]
            public virtual RepoItemInfo Address1Info
            {
                get
                {
                    return _address1Info;
                }
            }

            /// <summary>
            /// The Address2 item.
            /// </summary>
            [RepositoryItem("57000dea-7599-4f06-be09-a5541de2ef23")]
            public virtual Ranorex.InputTag Address2
            {
                get
                {
                    return _address2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Address2 item info.
            /// </summary>
            [RepositoryItemInfo("57000dea-7599-4f06-be09-a5541de2ef23")]
            public virtual RepoItemInfo Address2Info
            {
                get
                {
                    return _address2Info;
                }
            }

            /// <summary>
            /// The City item.
            /// </summary>
            [RepositoryItem("8057cedb-5b61-40a2-ac92-d5645721ca67")]
            public virtual Ranorex.InputTag City
            {
                get
                {
                    return _cityInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The City item info.
            /// </summary>
            [RepositoryItemInfo("8057cedb-5b61-40a2-ac92-d5645721ca67")]
            public virtual RepoItemInfo CityInfo
            {
                get
                {
                    return _cityInfo;
                }
            }

            /// <summary>
            /// The Register1 item.
            /// </summary>
            [RepositoryItem("b5f06ee8-ac11-4330-b54e-6e457d383b4e")]
            public virtual Ranorex.InputTag Register1
            {
                get
                {
                    return _register1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Register1 item info.
            /// </summary>
            [RepositoryItemInfo("b5f06ee8-ac11-4330-b54e-6e457d383b4e")]
            public virtual RepoItemInfo Register1Info
            {
                get
                {
                    return _register1Info;
                }
            }

            /// <summary>
            /// The BTagDearShreyataSugandhi item.
            /// </summary>
            [RepositoryItem("8c93d372-8c1d-4137-b4fa-9a11d4f4c205")]
            public virtual Ranorex.BTag BTagDearShreyataSugandhi
            {
                get
                {
                    return _btagdearshreyatasugandhiInfo.CreateAdapter<Ranorex.BTag>(true);
                }
            }

            /// <summary>
            /// The BTagDearShreyataSugandhi item info.
            /// </summary>
            [RepositoryItemInfo("8c93d372-8c1d-4137-b4fa-9a11d4f4c205")]
            public virtual RepoItemInfo BTagDearShreyataSugandhiInfo
            {
                get
                {
                    return _btagdearshreyatasugandhiInfo;
                }
            }

            /// <summary>
            /// The TripType item.
            /// </summary>
            [RepositoryItem("d8ba1f43-f041-4d2a-9344-ce505f9def37")]
            public virtual Ranorex.InputTag TripType
            {
                get
                {
                    return _triptypeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TripType item info.
            /// </summary>
            [RepositoryItemInfo("d8ba1f43-f041-4d2a-9344-ce505f9def37")]
            public virtual RepoItemInfo TripTypeInfo
            {
                get
                {
                    return _triptypeInfo;
                }
            }

            /// <summary>
            /// The TripType1 item.
            /// </summary>
            [RepositoryItem("cb4a294d-5af2-42a8-a215-be2464843a04")]
            public virtual Ranorex.InputTag TripType1
            {
                get
                {
                    return _triptype1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TripType1 item info.
            /// </summary>
            [RepositoryItemInfo("cb4a294d-5af2-42a8-a215-be2464843a04")]
            public virtual RepoItemInfo TripType1Info
            {
                get
                {
                    return _triptype1Info;
                }
            }

            /// <summary>
            /// The PassCount item.
            /// </summary>
            [RepositoryItem("1be40ccf-9106-47e0-8c4f-a88729aeb82b")]
            public virtual Ranorex.SelectTag PassCount
            {
                get
                {
                    return _passcountInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The PassCount item info.
            /// </summary>
            [RepositoryItemInfo("1be40ccf-9106-47e0-8c4f-a88729aeb82b")]
            public virtual RepoItemInfo PassCountInfo
            {
                get
                {
                    return _passcountInfo;
                }
            }

            /// <summary>
            /// The FromPort item.
            /// </summary>
            [RepositoryItem("d6cacf91-b0f2-4ba0-a54d-8dd4a6c4911d")]
            public virtual Ranorex.SelectTag FromPort
            {
                get
                {
                    return _fromportInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The FromPort item info.
            /// </summary>
            [RepositoryItemInfo("d6cacf91-b0f2-4ba0-a54d-8dd4a6c4911d")]
            public virtual RepoItemInfo FromPortInfo
            {
                get
                {
                    return _fromportInfo;
                }
            }

            /// <summary>
            /// The FromMonth item.
            /// </summary>
            [RepositoryItem("df5dfc32-d492-4000-893d-b53874334b8f")]
            public virtual Ranorex.SelectTag FromMonth
            {
                get
                {
                    return _frommonthInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The FromMonth item info.
            /// </summary>
            [RepositoryItemInfo("df5dfc32-d492-4000-893d-b53874334b8f")]
            public virtual RepoItemInfo FromMonthInfo
            {
                get
                {
                    return _frommonthInfo;
                }
            }

            /// <summary>
            /// The FromDay item.
            /// </summary>
            [RepositoryItem("47c118ae-a58b-4cfa-8b2c-ea8b9cc647fc")]
            public virtual Ranorex.SelectTag FromDay
            {
                get
                {
                    return _fromdayInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The FromDay item info.
            /// </summary>
            [RepositoryItemInfo("47c118ae-a58b-4cfa-8b2c-ea8b9cc647fc")]
            public virtual RepoItemInfo FromDayInfo
            {
                get
                {
                    return _fromdayInfo;
                }
            }

            /// <summary>
            /// The ToPort item.
            /// </summary>
            [RepositoryItem("bd05b57c-438d-4672-bab8-784c7ad568fb")]
            public virtual Ranorex.SelectTag ToPort
            {
                get
                {
                    return _toportInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The ToPort item info.
            /// </summary>
            [RepositoryItemInfo("bd05b57c-438d-4672-bab8-784c7ad568fb")]
            public virtual RepoItemInfo ToPortInfo
            {
                get
                {
                    return _toportInfo;
                }
            }

            /// <summary>
            /// The ToMonth item.
            /// </summary>
            [RepositoryItem("aed7bfc5-c1dd-43d8-8c81-3cb2a233dff5")]
            public virtual Ranorex.SelectTag ToMonth
            {
                get
                {
                    return _tomonthInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The ToMonth item info.
            /// </summary>
            [RepositoryItemInfo("aed7bfc5-c1dd-43d8-8c81-3cb2a233dff5")]
            public virtual RepoItemInfo ToMonthInfo
            {
                get
                {
                    return _tomonthInfo;
                }
            }

            /// <summary>
            /// The ToDay item.
            /// </summary>
            [RepositoryItem("556bf797-0aba-46de-8c45-9d5b9883aca1")]
            public virtual Ranorex.SelectTag ToDay
            {
                get
                {
                    return _todayInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The ToDay item info.
            /// </summary>
            [RepositoryItemInfo("556bf797-0aba-46de-8c45-9d5b9883aca1")]
            public virtual RepoItemInfo ToDayInfo
            {
                get
                {
                    return _todayInfo;
                }
            }

            /// <summary>
            /// The ServClass item.
            /// </summary>
            [RepositoryItem("b48688bc-9871-443c-b6a5-b806f5293c3b")]
            public virtual Ranorex.InputTag ServClass
            {
                get
                {
                    return _servclassInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ServClass item info.
            /// </summary>
            [RepositoryItemInfo("b48688bc-9871-443c-b6a5-b806f5293c3b")]
            public virtual RepoItemInfo ServClassInfo
            {
                get
                {
                    return _servclassInfo;
                }
            }

            /// <summary>
            /// The Airline item.
            /// </summary>
            [RepositoryItem("5b760db6-40b5-4d99-8754-041ed2c4ba4c")]
            public virtual Ranorex.SelectTag Airline
            {
                get
                {
                    return _airlineInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Airline item info.
            /// </summary>
            [RepositoryItemInfo("5b760db6-40b5-4d99-8754-041ed2c4ba4c")]
            public virtual RepoItemInfo AirlineInfo
            {
                get
                {
                    return _airlineInfo;
                }
            }

            /// <summary>
            /// The FindFlights item.
            /// </summary>
            [RepositoryItem("6026656f-fe3b-485b-8f0d-6e6b34a6b11b")]
            public virtual Ranorex.InputTag FindFlights
            {
                get
                {
                    return _findflightsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FindFlights item info.
            /// </summary>
            [RepositoryItemInfo("6026656f-fe3b-485b-8f0d-6e6b34a6b11b")]
            public virtual RepoItemInfo FindFlightsInfo
            {
                get
                {
                    return _findflightsInfo;
                }
            }

            /// <summary>
            /// The OutFlight item.
            /// </summary>
            [RepositoryItem("d60828d3-301e-40a6-9d99-51b88deae4c9")]
            public virtual Ranorex.InputTag OutFlight
            {
                get
                {
                    return _outflightInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The OutFlight item info.
            /// </summary>
            [RepositoryItemInfo("d60828d3-301e-40a6-9d99-51b88deae4c9")]
            public virtual RepoItemInfo OutFlightInfo
            {
                get
                {
                    return _outflightInfo;
                }
            }

            /// <summary>
            /// The InFlight item.
            /// </summary>
            [RepositoryItem("4bea2c69-8bc9-42b8-9290-53945d909217")]
            public virtual Ranorex.InputTag InFlight
            {
                get
                {
                    return _inflightInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InFlight item info.
            /// </summary>
            [RepositoryItemInfo("4bea2c69-8bc9-42b8-9290-53945d909217")]
            public virtual RepoItemInfo InFlightInfo
            {
                get
                {
                    return _inflightInfo;
                }
            }

            /// <summary>
            /// The ReserveFlights item.
            /// </summary>
            [RepositoryItem("11cad15f-c3e0-4fcf-8abe-5dabdcee54d1")]
            public virtual Ranorex.InputTag ReserveFlights
            {
                get
                {
                    return _reserveflightsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ReserveFlights item info.
            /// </summary>
            [RepositoryItemInfo("11cad15f-c3e0-4fcf-8abe-5dabdcee54d1")]
            public virtual RepoItemInfo ReserveFlightsInfo
            {
                get
                {
                    return _reserveflightsInfo;
                }
            }

            /// <summary>
            /// The PassFirst0 item.
            /// </summary>
            [RepositoryItem("cff623a5-28b6-4f80-8e25-08a0373bd1b8")]
            public virtual Ranorex.InputTag PassFirst0
            {
                get
                {
                    return _passfirst0Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PassFirst0 item info.
            /// </summary>
            [RepositoryItemInfo("cff623a5-28b6-4f80-8e25-08a0373bd1b8")]
            public virtual RepoItemInfo PassFirst0Info
            {
                get
                {
                    return _passfirst0Info;
                }
            }

            /// <summary>
            /// The PassLast0 item.
            /// </summary>
            [RepositoryItem("90df8166-67ff-4dc7-a071-9e612d7b72b3")]
            public virtual Ranorex.InputTag PassLast0
            {
                get
                {
                    return _passlast0Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PassLast0 item info.
            /// </summary>
            [RepositoryItemInfo("90df8166-67ff-4dc7-a071-9e612d7b72b3")]
            public virtual RepoItemInfo PassLast0Info
            {
                get
                {
                    return _passlast0Info;
                }
            }

            /// <summary>
            /// The Pass0Meal item.
            /// </summary>
            [RepositoryItem("71bdde25-ef8b-4f68-aad3-e4078c84b576")]
            public virtual Ranorex.SelectTag Pass0Meal
            {
                get
                {
                    return _pass0mealInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Pass0Meal item info.
            /// </summary>
            [RepositoryItemInfo("71bdde25-ef8b-4f68-aad3-e4078c84b576")]
            public virtual RepoItemInfo Pass0MealInfo
            {
                get
                {
                    return _pass0mealInfo;
                }
            }

            /// <summary>
            /// The PassFirst1 item.
            /// </summary>
            [RepositoryItem("dea3851b-c9e3-4997-8660-4a961a47ff25")]
            public virtual Ranorex.InputTag PassFirst1
            {
                get
                {
                    return _passfirst1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PassFirst1 item info.
            /// </summary>
            [RepositoryItemInfo("dea3851b-c9e3-4997-8660-4a961a47ff25")]
            public virtual RepoItemInfo PassFirst1Info
            {
                get
                {
                    return _passfirst1Info;
                }
            }

            /// <summary>
            /// The PassLast1 item.
            /// </summary>
            [RepositoryItem("7894f957-e52c-466a-9a5e-329c914e61c0")]
            public virtual Ranorex.InputTag PassLast1
            {
                get
                {
                    return _passlast1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PassLast1 item info.
            /// </summary>
            [RepositoryItemInfo("7894f957-e52c-466a-9a5e-329c914e61c0")]
            public virtual RepoItemInfo PassLast1Info
            {
                get
                {
                    return _passlast1Info;
                }
            }

            /// <summary>
            /// The Pass1Meal item.
            /// </summary>
            [RepositoryItem("1a18057a-1946-4d66-80e7-72ca69f849d0")]
            public virtual Ranorex.SelectTag Pass1Meal
            {
                get
                {
                    return _pass1mealInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Pass1Meal item info.
            /// </summary>
            [RepositoryItemInfo("1a18057a-1946-4d66-80e7-72ca69f849d0")]
            public virtual RepoItemInfo Pass1MealInfo
            {
                get
                {
                    return _pass1mealInfo;
                }
            }

            /// <summary>
            /// The PassFirst2 item.
            /// </summary>
            [RepositoryItem("b56f2968-a9c7-44fe-9e1f-a73c7cbe0d79")]
            public virtual Ranorex.InputTag PassFirst2
            {
                get
                {
                    return _passfirst2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PassFirst2 item info.
            /// </summary>
            [RepositoryItemInfo("b56f2968-a9c7-44fe-9e1f-a73c7cbe0d79")]
            public virtual RepoItemInfo PassFirst2Info
            {
                get
                {
                    return _passfirst2Info;
                }
            }

            /// <summary>
            /// The PassLast2 item.
            /// </summary>
            [RepositoryItem("f51c3172-72a2-4468-8b79-907490a60b4b")]
            public virtual Ranorex.InputTag PassLast2
            {
                get
                {
                    return _passlast2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PassLast2 item info.
            /// </summary>
            [RepositoryItemInfo("f51c3172-72a2-4468-8b79-907490a60b4b")]
            public virtual RepoItemInfo PassLast2Info
            {
                get
                {
                    return _passlast2Info;
                }
            }

            /// <summary>
            /// The Pass2Meal item.
            /// </summary>
            [RepositoryItem("461baf8c-48df-4d0d-ba30-f2919be1fcac")]
            public virtual Ranorex.SelectTag Pass2Meal
            {
                get
                {
                    return _pass2mealInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Pass2Meal item info.
            /// </summary>
            [RepositoryItemInfo("461baf8c-48df-4d0d-ba30-f2919be1fcac")]
            public virtual RepoItemInfo Pass2MealInfo
            {
                get
                {
                    return _pass2mealInfo;
                }
            }

            /// <summary>
            /// The Creditnumber item.
            /// </summary>
            [RepositoryItem("2b1d4cdc-854c-4f92-953f-fe74eddbfb2b")]
            public virtual Ranorex.InputTag Creditnumber
            {
                get
                {
                    return _creditnumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Creditnumber item info.
            /// </summary>
            [RepositoryItemInfo("2b1d4cdc-854c-4f92-953f-fe74eddbfb2b")]
            public virtual RepoItemInfo CreditnumberInfo
            {
                get
                {
                    return _creditnumberInfo;
                }
            }

            /// <summary>
            /// The BuyFlights item.
            /// </summary>
            [RepositoryItem("2a0aa8ac-27ff-427c-b01a-abb6bf894b1f")]
            public virtual Ranorex.InputTag BuyFlights
            {
                get
                {
                    return _buyflightsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BuyFlights item info.
            /// </summary>
            [RepositoryItemInfo("2a0aa8ac-27ff-427c-b01a-abb6bf894b1f")]
            public virtual RepoItemInfo BuyFlightsInfo
            {
                get
                {
                    return _buyflightsInfo;
                }
            }

            /// <summary>
            /// The YourItineraryHasBeenBooked item.
            /// </summary>
            [RepositoryItem("7fb24d00-2a0f-46f3-9076-6090b5a56329")]
            public virtual Ranorex.FontTag YourItineraryHasBeenBooked
            {
                get
                {
                    return _youritineraryhasbeenbookedInfo.CreateAdapter<Ranorex.FontTag>(true);
                }
            }

            /// <summary>
            /// The YourItineraryHasBeenBooked item info.
            /// </summary>
            [RepositoryItemInfo("7fb24d00-2a0f-46f3-9076-6090b5a56329")]
            public virtual RepoItemInfo YourItineraryHasBeenBookedInfo
            {
                get
                {
                    return _youritineraryhasbeenbookedInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("30415600-3f5f-4e97-aba2-9e3aba19bc98")]
            public virtual Ranorex.InputTag UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("30415600-3f5f-4e97-aba2-9e3aba19bc98")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("473fc299-e75d-4195-9473-a10812cc6390")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("473fc299-e75d-4195-9473-a10812cc6390")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("96f482fc-bbfe-4b4f-bc33-fda34d0e1f9d")]
            public virtual Ranorex.InputTag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("96f482fc-bbfe-4b4f-bc33-fda34d0e1f9d")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The HttpNewtoursDemoautComImagesMasts item.
            /// </summary>
            [RepositoryItem("8f0192e4-22fb-4cab-a19e-5a642dbadf0a")]
            public virtual Ranorex.ImgTag HttpNewtoursDemoautComImagesMasts
            {
                get
                {
                    return _httpnewtoursdemoautcomimagesmastsInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpNewtoursDemoautComImagesMasts item info.
            /// </summary>
            [RepositoryItemInfo("8f0192e4-22fb-4cab-a19e-5a642dbadf0a")]
            public virtual RepoItemInfo HttpNewtoursDemoautComImagesMastsInfo
            {
                get
                {
                    return _httpnewtoursdemoautcomimagesmastsInfo;
                }
            }
        }

        /// <summary>
        /// The SelectboxAppFolder folder.
        /// </summary>
        [RepositoryFolder("a8758683-e4f6-4e37-b887-b44b5493d8a1")]
        public partial class SelectboxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _hinduInfo;
            RepoItemInfo _indiaInfo;

            /// <summary>
            /// Creates a new Selectbox  folder.
            /// </summary>
            public SelectboxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Selectbox", "/container[@caption='selectbox']", parentFolder, 30000, null, true, "a8758683-e4f6-4e37-b887-b44b5493d8a1", "")
            {
                _hinduInfo = new RepoItemInfo(this, "Hindu", "listitem[@accessiblename='Hindu']", 30000, null, "63ee366f-006d-453c-ba83-6d457582c8cb");
                _indiaInfo = new RepoItemInfo(this, "INDIA", "listitem[@accessiblename='INDIA']", 30000, null, "f9a26d08-98f6-42e1-b386-b2ea0952d2a1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a8758683-e4f6-4e37-b887-b44b5493d8a1")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a8758683-e4f6-4e37-b887-b44b5493d8a1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Hindu item.
            /// </summary>
            [RepositoryItem("63ee366f-006d-453c-ba83-6d457582c8cb")]
            public virtual Ranorex.ListItem Hindu
            {
                get
                {
                    return _hinduInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Hindu item info.
            /// </summary>
            [RepositoryItemInfo("63ee366f-006d-453c-ba83-6d457582c8cb")]
            public virtual RepoItemInfo HinduInfo
            {
                get
                {
                    return _hinduInfo;
                }
            }

            /// <summary>
            /// The INDIA item.
            /// </summary>
            [RepositoryItem("f9a26d08-98f6-42e1-b386-b2ea0952d2a1")]
            public virtual Ranorex.ListItem INDIA
            {
                get
                {
                    return _indiaInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The INDIA item info.
            /// </summary>
            [RepositoryItemInfo("f9a26d08-98f6-42e1-b386-b2ea0952d2a1")]
            public virtual RepoItemInfo INDIAInfo
            {
                get
                {
                    return _indiaInfo;
                }
            }
        }

        /// <summary>
        /// The FindAFlightMercuryToursInternetAppFolder folder.
        /// </summary>
        [RepositoryFolder("80de4d1e-490c-4299-8eb7-6e6e6dcabd5b")]
        public partial class FindAFlightMercuryToursInternetAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clientcaptionInfo;

            /// <summary>
            /// Creates a new FindAFlightMercuryToursInternet  folder.
            /// </summary>
            public FindAFlightMercuryToursInternetAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FindAFlightMercuryToursInternet", "/form[@title~'^Find\\ a\\ Flight:\\ Mercury\\ To']", parentFolder, 30000, null, true, "80de4d1e-490c-4299-8eb7-6e6e6dcabd5b", "")
            {
                _clientcaptionInfo = new RepoItemInfo(this, "ClientCaption", "element[@class='Client Caption']", 30000, null, "59ef1260-4506-4ce8-960e-47600f98e54d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("80de4d1e-490c-4299-8eb7-6e6e6dcabd5b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("80de4d1e-490c-4299-8eb7-6e6e6dcabd5b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ClientCaption item.
            /// </summary>
            [RepositoryItem("59ef1260-4506-4ce8-960e-47600f98e54d")]
            public virtual Ranorex.Unknown ClientCaption
            {
                get
                {
                    return _clientcaptionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ClientCaption item info.
            /// </summary>
            [RepositoryItemInfo("59ef1260-4506-4ce8-960e-47600f98e54d")]
            public virtual RepoItemInfo ClientCaptionInfo
            {
                get
                {
                    return _clientcaptionInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}