///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DesktopTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DesktopTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("9da6b11e-c49b-4543-81ff-4bc495b30fb1")]
    public partial class DesktopTestRepository : RepoGenBaseFolder
    {
        static DesktopTestRepository instance = new DesktopTestRepository();
        DesktopTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        DesktopTestRepositoryFolders.List1000AppFolder _list1000;

        /// <summary>
        /// Gets the singleton class instance representing the DesktopTestRepository element repository.
        /// </summary>
        [RepositoryFolder("9da6b11e-c49b-4543-81ff-4bc495b30fb1")]
        public static DesktopTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DesktopTestRepository() 
            : base("DesktopTestRepository", "/", null, 0, false, "9da6b11e-c49b-4543-81ff-4bc495b30fb1", ".\\RepositoryImages\\DesktopTestRepository9da6b11e.rximgres")
        {
            _applicationundertest = new DesktopTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _list1000 = new DesktopTestRepositoryFolders.List1000AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9da6b11e-c49b-4543-81ff-4bc495b30fb1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("6816f6c5-9943-43e2-a73f-8b90d0c9dc47")]
        public virtual DesktopTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("2eef8bd8-20f8-403a-89fa-9bbcecde2cc3")]
        public virtual DesktopTestRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class DesktopTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("6816f6c5-9943-43e2-a73f-8b90d0c9dc47")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            DesktopTestRepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;
            DesktopTestRepositoryFolders.RxTabStandardFolder _rxtabstandard;
            RepoItemInfo _testdatabasetabInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/form[@processname='RxDemoApp']", parentFolder, 30000, null, true, "6816f6c5-9943-43e2-a73f-8b90d0c9dc47", "")
            {
                _rxtabintroduction = new DesktopTestRepositoryFolders.RxTabIntroductionFolder(this);
                _rxtabstandard = new DesktopTestRepositoryFolders.RxTabStandardFolder(this);
                _testdatabasetabInfo = new RepoItemInfo(this, "TestDatabaseTab", "?/?/tabpage[@accessiblename='Test database']", 30000, null, "ac8dddaf-df36-4d78-b51c-a379cc31651b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6816f6c5-9943-43e2-a73f-8b90d0c9dc47")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6816f6c5-9943-43e2-a73f-8b90d0c9dc47")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TestDatabaseTab item.
            /// </summary>
            [RepositoryItem("ac8dddaf-df36-4d78-b51c-a379cc31651b")]
            public virtual Ranorex.TabPage TestDatabaseTab
            {
                get
                {
                    return _testdatabasetabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabaseTab item info.
            /// </summary>
            [RepositoryItemInfo("ac8dddaf-df36-4d78-b51c-a379cc31651b")]
            public virtual RepoItemInfo TestDatabaseTabInfo
            {
                get
                {
                    return _testdatabasetabInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("ce6dfbd6-9b9e-43ba-9d3c-3fd4d42faf2e")]
            public virtual DesktopTestRepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }

            /// <summary>
            /// The RxTabStandard folder.
            /// </summary>
            [RepositoryFolder("2e5b8a5a-0de2-4111-ad88-3681262aea43")]
            public virtual DesktopTestRepositoryFolders.RxTabStandardFolder RxTabStandard
            {
                get { return _rxtabstandard; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("ce6dfbd6-9b9e-43ba-9d3c-3fd4d42faf2e")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitInfo;
            RepoItemInfo _lblwelcomemessageInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "ce6dfbd6-9b9e-43ba-9d3c-3fd4d42faf2e", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/text[@accessiblename='Enter your name']", 30000, null, "4a8cc081-8b32-4ec2-98f0-17c5fac45285");
                _btnsubmitInfo = new RepoItemInfo(this, "BtnSubmit", "button[@controlname='btnSubmitUserName']", 30000, null, "7be6689c-098e-4b64-a0e2-692658c4a2b4");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "text[@controlname='lblWelcomeMessage']", 30000, null, "21201aa8-dd01-4009-a8ab-a0b7cd5de279");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ce6dfbd6-9b9e-43ba-9d3c-3fd4d42faf2e")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ce6dfbd6-9b9e-43ba-9d3c-3fd4d42faf2e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("4a8cc081-8b32-4ec2-98f0-17c5fac45285")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("4a8cc081-8b32-4ec2-98f0-17c5fac45285")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmit item.
            /// </summary>
            [RepositoryItem("7be6689c-098e-4b64-a0e2-692658c4a2b4")]
            public virtual Ranorex.Button BtnSubmit
            {
                get
                {
                    return _btnsubmitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmit item info.
            /// </summary>
            [RepositoryItemInfo("7be6689c-098e-4b64-a0e2-692658c4a2b4")]
            public virtual RepoItemInfo BtnSubmitInfo
            {
                get
                {
                    return _btnsubmitInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("21201aa8-dd01-4009-a8ab-a0b7cd5de279")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("21201aa8-dd01-4009-a8ab-a0b7cd5de279")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabStandardFolder folder.
        /// </summary>
        [RepositoryFolder("2e5b8a5a-0de2-4111-ad88-3681262aea43")]
        public partial class RxTabStandardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openInfo;
            RepoItemInfo _rdbfemaleInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _departmentInfo;
            RepoItemInfo _agetextboxInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _btndeletepersonInfo;
            RepoItemInfo _downInfo;
            RepoItemInfo _buttonupInfo;
            RepoItemInfo _shreyatasugandhifemale20testingInfo;
            RepoItemInfo _lblnumberofpersonsnumberInfo;
            RepoItemInfo _list0Info;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new RxTabStandard  folder.
            /// </summary>
            public RxTabStandardFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "2e5b8a5a-0de2-4111-ad88-3681262aea43", "")
            {
                _openInfo = new RepoItemInfo(this, "Open", "?/?/button[@accessiblename='Open']", 30000, null, "66145dde-6794-4348-9944-655dea20a303");
                _rdbfemaleInfo = new RepoItemInfo(this, "RdbFemale", "?/?/radiobutton[@controlname='rdbFemale']", 30000, null, "cf8991fe-cd50-4730-a746-6167c1cc618a");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", 30000, null, "80930eaa-f54d-4fb7-a74d-3252d07d36f2");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", 30000, null, "cc1813e1-1a96-4444-b320-4a21ad4411eb");
                _departmentInfo = new RepoItemInfo(this, "Department", "?/?/text[@controlid='1001']", 30000, null, "5e026e84-69d3-4052-a906-a1c7d13631d9");
                _agetextboxInfo = new RepoItemInfo(this, "AgeTextBox", "?/?/text[@controlname='upDownEdit']", 30000, null, "da809012-c41a-42e2-b79d-d0f7700b6999");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "button[@controlname='btnAddPerson']", 30000, null, "44934a7c-d2fb-449c-85ab-d94bf78794da");
                _btndeletepersonInfo = new RepoItemInfo(this, "BtnDeletePerson", "button[@controlname='btnDeletePerson']", 30000, null, "c9317def-7310-4f69-8700-742eba9d1eec");
                _downInfo = new RepoItemInfo(this, "Down", "container[@controlname='txtAge']/?/?/button[@accessiblename='Down']", 30000, null, "388942b6-1262-45d7-99c4-2c429d6daa29");
                _buttonupInfo = new RepoItemInfo(this, "ButtonUp", "container[@controlname='txtAge']/?/?/button[@accessiblename='Up']", 30000, null, "de4296f3-7eaa-4aba-bb13-ba8dfea8fe69");
                _shreyatasugandhifemale20testingInfo = new RepoItemInfo(this, "ShreyataSugandhiFemale20Testing", "list[@controlname='lstPersonList']/?/?/listitem[@accessiblename~'^Shreyata\\ Sugandhi\\ \\(female']", 30000, null, "866557e3-0215-4867-9a5d-4e8caa726316");
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", "text[@controlname='lblNumberOfPersonsNumber']", 30000, null, "b47d2c50-950e-4020-b9e7-5771f0292869");
                _list0Info = new RepoItemInfo(this, "List0", "?/?/list[@accessiblename='0']", 30000, null, "06b943a6-1f50-46d9-a270-627b1c8aa6ce");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button", 30000, null, "c3d8231f-9224-4395-95d6-c6e32271ab1f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2e5b8a5a-0de2-4111-ad88-3681262aea43")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2e5b8a5a-0de2-4111-ad88-3681262aea43")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("66145dde-6794-4348-9944-655dea20a303")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("66145dde-6794-4348-9944-655dea20a303")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The RdbFemale item.
            /// </summary>
            [RepositoryItem("cf8991fe-cd50-4730-a746-6167c1cc618a")]
            public virtual Ranorex.RadioButton RdbFemale
            {
                get
                {
                    return _rdbfemaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbFemale item info.
            /// </summary>
            [RepositoryItemInfo("cf8991fe-cd50-4730-a746-6167c1cc618a")]
            public virtual RepoItemInfo RdbFemaleInfo
            {
                get
                {
                    return _rdbfemaleInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("80930eaa-f54d-4fb7-a74d-3252d07d36f2")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("80930eaa-f54d-4fb7-a74d-3252d07d36f2")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("cc1813e1-1a96-4444-b320-4a21ad4411eb")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("cc1813e1-1a96-4444-b320-4a21ad4411eb")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Department item.
            /// </summary>
            [RepositoryItem("5e026e84-69d3-4052-a906-a1c7d13631d9")]
            public virtual Ranorex.Text Department
            {
                get
                {
                    return _departmentInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Department item info.
            /// </summary>
            [RepositoryItemInfo("5e026e84-69d3-4052-a906-a1c7d13631d9")]
            public virtual RepoItemInfo DepartmentInfo
            {
                get
                {
                    return _departmentInfo;
                }
            }

            /// <summary>
            /// The AgeTextBox item.
            /// </summary>
            [RepositoryItem("da809012-c41a-42e2-b79d-d0f7700b6999")]
            public virtual Ranorex.Text AgeTextBox
            {
                get
                {
                    return _agetextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AgeTextBox item info.
            /// </summary>
            [RepositoryItemInfo("da809012-c41a-42e2-b79d-d0f7700b6999")]
            public virtual RepoItemInfo AgeTextBoxInfo
            {
                get
                {
                    return _agetextboxInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("44934a7c-d2fb-449c-85ab-d94bf78794da")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("44934a7c-d2fb-449c-85ab-d94bf78794da")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The BtnDeletePerson item.
            /// </summary>
            [RepositoryItem("c9317def-7310-4f69-8700-742eba9d1eec")]
            public virtual Ranorex.Button BtnDeletePerson
            {
                get
                {
                    return _btndeletepersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDeletePerson item info.
            /// </summary>
            [RepositoryItemInfo("c9317def-7310-4f69-8700-742eba9d1eec")]
            public virtual RepoItemInfo BtnDeletePersonInfo
            {
                get
                {
                    return _btndeletepersonInfo;
                }
            }

            /// <summary>
            /// The Down item.
            /// </summary>
            [RepositoryItem("388942b6-1262-45d7-99c4-2c429d6daa29")]
            public virtual Ranorex.Button Down
            {
                get
                {
                    return _downInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Down item info.
            /// </summary>
            [RepositoryItemInfo("388942b6-1262-45d7-99c4-2c429d6daa29")]
            public virtual RepoItemInfo DownInfo
            {
                get
                {
                    return _downInfo;
                }
            }

            /// <summary>
            /// The ButtonUp item.
            /// </summary>
            [RepositoryItem("de4296f3-7eaa-4aba-bb13-ba8dfea8fe69")]
            public virtual Ranorex.Button ButtonUp
            {
                get
                {
                    return _buttonupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonUp item info.
            /// </summary>
            [RepositoryItemInfo("de4296f3-7eaa-4aba-bb13-ba8dfea8fe69")]
            public virtual RepoItemInfo ButtonUpInfo
            {
                get
                {
                    return _buttonupInfo;
                }
            }

            /// <summary>
            /// The ShreyataSugandhiFemale20Testing item.
            /// </summary>
            [RepositoryItem("866557e3-0215-4867-9a5d-4e8caa726316")]
            public virtual Ranorex.ListItem ShreyataSugandhiFemale20Testing
            {
                get
                {
                    return _shreyatasugandhifemale20testingInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ShreyataSugandhiFemale20Testing item info.
            /// </summary>
            [RepositoryItemInfo("866557e3-0215-4867-9a5d-4e8caa726316")]
            public virtual RepoItemInfo ShreyataSugandhiFemale20TestingInfo
            {
                get
                {
                    return _shreyatasugandhifemale20testingInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("b47d2c50-950e-4020-b9e7-5771f0292869")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("b47d2c50-950e-4020-b9e7-5771f0292869")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }

            /// <summary>
            /// The List0 item.
            /// </summary>
            [RepositoryItem("06b943a6-1f50-46d9-a270-627b1c8aa6ce")]
            public virtual Ranorex.List List0
            {
                get
                {
                    return _list0Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The List0 item info.
            /// </summary>
            [RepositoryItemInfo("06b943a6-1f50-46d9-a270-627b1c8aa6ce")]
            public virtual RepoItemInfo List0Info
            {
                get
                {
                    return _list0Info;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("c3d8231f-9224-4395-95d6-c6e32271ab1f")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("c3d8231f-9224-4395-95d6-c6e32271ab1f")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("2eef8bd8-20f8-403a-89fa-9bbcecde2cc3")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _testingInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "2eef8bd8-20f8-403a-89fa-9bbcecde2cc3", "")
            {
                _testingInfo = new RepoItemInfo(this, "Testing", "listitem[@text='Testing']", 30000, null, "ea8e822c-1d46-49b3-9e2a-10084a0deaf1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2eef8bd8-20f8-403a-89fa-9bbcecde2cc3")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2eef8bd8-20f8-403a-89fa-9bbcecde2cc3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Testing item.
            /// </summary>
            [RepositoryItem("ea8e822c-1d46-49b3-9e2a-10084a0deaf1")]
            public virtual Ranorex.ListItem Testing
            {
                get
                {
                    return _testingInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Testing item info.
            /// </summary>
            [RepositoryItemInfo("ea8e822c-1d46-49b3-9e2a-10084a0deaf1")]
            public virtual RepoItemInfo TestingInfo
            {
                get
                {
                    return _testingInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}