///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DesktopTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Intro_Tab recording.
    /// </summary>
    [TestModule("e7625ad3-e90a-4cdf-9885-4e51ebc89cdf", ModuleType.Recording, 1)]
    public partial class Intro_Tab : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DesktopTestRepository repository.
        /// </summary>
        public static DesktopTestRepository repo = DesktopTestRepository.Instance;

        static Intro_Tab instance = new Intro_Tab();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Intro_Tab()
        {
            name = "Shreyata";
            welcomeMsg = "Welcome, Shreyata!";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Intro_Tab Instance
        {
            get { return instance; }
        }

#region Variables

        string _name;

        /// <summary>
        /// Gets or sets the value of variable name.
        /// </summary>
        [TestVariable("4d02ef2f-ccb0-4f13-ad56-1c7a7bcc3706")]
        public string name
        {
            get { return _name; }
            set { _name = value; }
        }

        string _welcomeMsg;

        /// <summary>
        /// Gets or sets the value of variable welcomeMsg.
        /// </summary>
        [TestVariable("71966480-9238-4cd4-8ba7-8e989e3fa566")]
        public string welcomeMsg
        {
            get { return _welcomeMsg; }
            set { _welcomeMsg = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabIntroduction.EnterYourName' at 63;12.", repo.ApplicationUnderTest.RxTabIntroduction.EnterYourNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.RxTabIntroduction.EnterYourName.Click("63;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$name' with focus on 'ApplicationUnderTest.RxTabIntroduction.EnterYourName'.", repo.ApplicationUnderTest.RxTabIntroduction.EnterYourNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.RxTabIntroduction.EnterYourName.PressKeys(name);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabIntroduction.BtnSubmit' at 41;13.", repo.ApplicationUnderTest.RxTabIntroduction.BtnSubmitInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RxTabIntroduction.BtnSubmit.Click("41;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$welcomeMsg) on item 'ApplicationUnderTest.RxTabIntroduction.LblWelcomeMessage'.", repo.ApplicationUnderTest.RxTabIntroduction.LblWelcomeMessageInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RxTabIntroduction.LblWelcomeMessageInfo, "Text", welcomeMsg);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
