///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DesktopTest.TestDatabaseTab
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddEntry recording.
    /// </summary>
    [TestModule("ef81b6ab-60bc-4a37-8ee9-52e42a2acc20", ModuleType.Recording, 1)]
    public partial class AddEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DesktopTest.DesktopTestRepository repository.
        /// </summary>
        public static global::DesktopTest.DesktopTestRepository repo = global::DesktopTest.DesktopTestRepository.Instance;

        static AddEntry instance = new AddEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddEntry()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddEntry Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.FirstName' at 117;6.", repo.ApplicationUnderTest.RxTabStandard.FirstNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.RxTabStandard.FirstName.Click("117;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Shreyata' with focus on 'ApplicationUnderTest.RxTabStandard.FirstName'.", repo.ApplicationUnderTest.RxTabStandard.FirstNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.RxTabStandard.FirstName.PressKeys("Shreyata");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.LastName' at 18;13.", repo.ApplicationUnderTest.RxTabStandard.LastNameInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RxTabStandard.LastName.Click("18;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Sugandhi' with focus on 'ApplicationUnderTest.RxTabStandard.LastName'.", repo.ApplicationUnderTest.RxTabStandard.LastNameInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.RxTabStandard.LastName.PressKeys("Sugandhi");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.Open' at 6;14.", repo.ApplicationUnderTest.RxTabStandard.OpenInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.RxTabStandard.Open.Click("6;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Testing' at 278;12.", repo.List1000.TestingInfo, new RecordItemIndex(5));
            repo.List1000.Testing.Click("278;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.AgeTextBox' at CenterRight.", repo.ApplicationUnderTest.RxTabStandard.AgeTextBoxInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.RxTabStandard.AgeTextBox.Click(Location.CenterRight);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'ApplicationUnderTest.RxTabStandard.AgeTextBox'.", repo.ApplicationUnderTest.RxTabStandard.AgeTextBoxInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.RxTabStandard.AgeTextBox.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '20' with focus on 'ApplicationUnderTest.RxTabStandard.AgeTextBox'.", repo.ApplicationUnderTest.RxTabStandard.AgeTextBoxInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.RxTabStandard.AgeTextBox.PressKeys("20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.RdbFemale' at 10;9.", repo.ApplicationUnderTest.RxTabStandard.RdbFemaleInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.RxTabStandard.RdbFemale.Click("10;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.BtnAddPerson' at 33;9.", repo.ApplicationUnderTest.RxTabStandard.BtnAddPersonInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.RxTabStandard.BtnAddPerson.Click("33;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Shreyata Sugandhi (female, 20) Testing') on item 'ApplicationUnderTest.RxTabStandard.ShreyataSugandhiFemale20Testing'.", repo.ApplicationUnderTest.RxTabStandard.ShreyataSugandhiFemale20TestingInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RxTabStandard.ShreyataSugandhiFemale20TestingInfo, "Text", "Shreyata Sugandhi (female, 20) Testing");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1') on item 'ApplicationUnderTest.RxTabStandard.LblNumberOfPersonsNumber'.", repo.ApplicationUnderTest.RxTabStandard.LblNumberOfPersonsNumberInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RxTabStandard.LblNumberOfPersonsNumberInfo, "Text", "1");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
