///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ImageRecording recording.
    /// </summary>
    [TestModule("5c7da9d9-b9d7-4ea5-8666-c336032a5e6c", ModuleType.Recording, 1)]
    public partial class ImageRecording : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestAppRepository repository.
        /// </summary>
        public static TestAppRepository repo = TestAppRepository.Instance;

        static ImageRecording instance = new ImageRecording();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ImageRecording()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ImageRecording Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ImageBasedAutomation' at 46;8.", repo.ApplicationUnderTest.ImageBasedAutomationInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.ImageBasedAutomation.Click("46;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabImageBased.MonthCalendar1' at 70;86.", repo.ApplicationUnderTest.RxTabImageBased.MonthCalendar1Info, new RecordItemIndex(1));
            repo.ApplicationUnderTest.RxTabImageBased.MonthCalendar1.Click("70;86");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabImageBased.MonthCalendar1' at 129;88.", repo.ApplicationUnderTest.RxTabImageBased.MonthCalendar1Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RxTabImageBased.MonthCalendar1.Click("129;88");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabImageBased.MonthCalendar1' at 196;103.", repo.ApplicationUnderTest.RxTabImageBased.MonthCalendar1Info, new RecordItemIndex(3));
            repo.ApplicationUnderTest.RxTabImageBased.MonthCalendar1.Click("196;103");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabImageBased.ChkShowImage' at 7;8.", repo.ApplicationUnderTest.RxTabImageBased.ChkShowImageInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.RxTabImageBased.ChkShowImage.Click("7;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=402,Height=263}) on item 'ApplicationUnderTest.RxTabImageBased.TheCat'.", repo.ApplicationUnderTest.RxTabImageBased.TheCatInfo, new RecordItemIndex(5));
            Validate.CompareImage(repo.ApplicationUnderTest.RxTabImageBased.TheCatInfo, TheCat_Screenshot1, TheCat_Screenshot1_Options);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        CompressedImage TheCat_Screenshot1
        { get { return repo.ApplicationUnderTest.RxTabImageBased.TheCatInfo.GetScreenshot1(new Rectangle(0, 0, 402, 263)); } }

        Imaging.FindOptions TheCat_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,402,263;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
