///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("45c8e318-9d92-42a9-8662-7eed5094441e", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestAppRepository repository.
        /// </summary>
        public static TestAppRepository repo = TestAppRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            name = "SS";
            msg = "yourValue";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _name;

        /// <summary>
        /// Gets or sets the value of variable name.
        /// </summary>
        [TestVariable("8ac799d4-4aac-4d2c-8d05-377b63e40165")]
        public string name
        {
            get { return _name; }
            set { _name = value; }
        }

        string _msg;

        /// <summary>
        /// Gets or sets the value of variable msg.
        /// </summary>
        [TestVariable("a94a2349-2118-426e-94b5-2a446bd1daaa")]
        public string msg
        {
            get { return _msg; }
            set { _msg = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxBoxName' at Center.", repo.ApplicationUnderTest.TxBoxNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.TxBoxName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$name' with focus on 'ApplicationUnderTest.TxBoxName'.", repo.ApplicationUnderTest.TxBoxNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.TxBoxName.PressKeys(name);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnSubmitUserName' at Center.", repo.ApplicationUnderTest.BtnSubmitUserNameInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.BtnSubmitUserName.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(3));
            //Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1s to exist. Associated repository item: 'ApplicationUnderTest.WelcomeMsg'", repo.ApplicationUnderTest.WelcomeMsgInfo, new ActionTimeout(1000), new RecordItemIndex(4));
            repo.ApplicationUnderTest.WelcomeMsgInfo.WaitForExists(1000);
            
            Validate_WelcomeMsg(repo.ApplicationUnderTest.WelcomeMsgInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
