///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestAppRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("cc9adede-d7d0-4f5b-ab4d-18520c5f51ba")]
    public partial class TestAppRepository : RepoGenBaseFolder
    {
        static TestAppRepository instance = new TestAppRepository();
        TestAppRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the TestAppRepository element repository.
        /// </summary>
        [RepositoryFolder("cc9adede-d7d0-4f5b-ab4d-18520c5f51ba")]
        public static TestAppRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestAppRepository() 
            : base("TestAppRepository", "/", null, 0, false, "cc9adede-d7d0-4f5b-ab4d-18520c5f51ba", ".\\RepositoryImages\\TestAppRepositorycc9adede.rximgres")
        {
            _applicationundertest = new TestAppRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("cc9adede-d7d0-4f5b-ab4d-18520c5f51ba")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("0c9ae9bd-05c0-4b86-9578-16bab511e54f")]
        public virtual TestAppRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class TestAppRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("0c9ae9bd-05c0-4b86-9578-16bab511e54f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            TestAppRepositoryFolders.RxTabImageBasedFolder _rxtabimagebased;
            RepoItemInfo _welcomemsgInfo;
            RepoItemInfo _txboxnameInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            ImageBasedAutomationInfoClass _imagebasedautomationInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/form[@processname='RxDemoApp']", parentFolder, 30000, null, true, "0c9ae9bd-05c0-4b86-9578-16bab511e54f", "")
            {
                _rxtabimagebased = new TestAppRepositoryFolders.RxTabImageBasedFolder(this);
                _welcomemsgInfo = new RepoItemInfo(this, "WelcomeMsg", ".//text[@controlname='lblWelcomeMessage' and @controltext~'^Welcome,.*!$']", 30000, null, "94e9a3ea-26ff-4873-8e26-3349fc60dc6b");
                _txboxnameInfo = new RepoItemInfo(this, "TxBoxName", ".//text[@accessiblename='Enter your name']", 30000, null, "c9e1b16b-52b6-4afb-a708-5938fdc40fc1");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "?/?/tabpage[@controlname='RxTabIntroduction']/button[@controlname='btnSubmitUserName']", 30000, null, "cbffc97a-a9e1-47a3-b0cb-bc0d5562abab");
                _imagebasedautomationInfo = new ImageBasedAutomationInfoClass(this);
            }

            /// <summary>
            /// The ImageBasedAutomationInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("fb1b7a81-49a3-4648-9f7e-dcbf033e2883")]
            public class ImageBasedAutomationInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ImageBasedAutomationInfoClass class constructor.
                /// </summary>
                public ImageBasedAutomationInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ImageBasedAutomation", "?/?/tabpage[@accessiblename='Image-based automation']", 30000, null, "fb1b7a81-49a3-4648-9f7e-dcbf033e2883")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("5445c077-4fd8-4d34-8cbd-bd18405dbd8c")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("5445c077-4fd8-4d34-8cbd-bd18405dbd8c");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("5445c077-4fd8-4d34-8cbd-bd18405dbd8c")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("5445c077-4fd8-4d34-8cbd-bd18405dbd8c", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("3bddfd38-0919-4803-bad2-a053ca016293")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("3bddfd38-0919-4803-bad2-a053ca016293");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("3bddfd38-0919-4803-bad2-a053ca016293")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("3bddfd38-0919-4803-bad2-a053ca016293", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0c9ae9bd-05c0-4b86-9578-16bab511e54f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0c9ae9bd-05c0-4b86-9578-16bab511e54f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WelcomeMsg item.
            /// </summary>
            [RepositoryItem("94e9a3ea-26ff-4873-8e26-3349fc60dc6b")]
            public virtual Ranorex.Text WelcomeMsg
            {
                get
                {
                    return _welcomemsgInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The WelcomeMsg item info.
            /// </summary>
            [RepositoryItemInfo("94e9a3ea-26ff-4873-8e26-3349fc60dc6b")]
            public virtual RepoItemInfo WelcomeMsgInfo
            {
                get
                {
                    return _welcomemsgInfo;
                }
            }

            /// <summary>
            /// The TxBoxName item.
            /// </summary>
            [RepositoryItem("c9e1b16b-52b6-4afb-a708-5938fdc40fc1")]
            public virtual Ranorex.Text TxBoxName
            {
                get
                {
                    return _txboxnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxBoxName item info.
            /// </summary>
            [RepositoryItemInfo("c9e1b16b-52b6-4afb-a708-5938fdc40fc1")]
            public virtual RepoItemInfo TxBoxNameInfo
            {
                get
                {
                    return _txboxnameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("cbffc97a-a9e1-47a3-b0cb-bc0d5562abab")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("cbffc97a-a9e1-47a3-b0cb-bc0d5562abab")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item.
            /// </summary>
            [RepositoryItem("fb1b7a81-49a3-4648-9f7e-dcbf033e2883")]
            public virtual Ranorex.TabPage ImageBasedAutomation
            {
                get
                {
                    return _imagebasedautomationInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item info.
            /// </summary>
            [RepositoryItemInfo("fb1b7a81-49a3-4648-9f7e-dcbf033e2883")]
            public virtual ImageBasedAutomationInfoClass ImageBasedAutomationInfo
            {
                get
                {
                    return _imagebasedautomationInfo;
                }
            }

            /// <summary>
            /// The RxTabImageBased folder.
            /// </summary>
            [RepositoryFolder("26e5a1bf-fc9d-4480-b23b-80b3ae79548a")]
            public virtual TestAppRepositoryFolders.RxTabImageBasedFolder RxTabImageBased
            {
                get { return _rxtabimagebased; }
            }
        }

        /// <summary>
        /// The RxTabImageBasedFolder folder.
        /// </summary>
        [RepositoryFolder("26e5a1bf-fc9d-4480-b23b-80b3ae79548a")]
        public partial class RxTabImageBasedFolder : RepoGenBaseFolder
        {
            MonthCalendar1InfoClass _monthcalendar1Info;
            ChkShowImageInfoClass _chkshowimageInfo;
            TheCatInfoClass _thecatInfo;
            RxTabImageBasedInfoClass _rxtabimagebasedInfo;

            /// <summary>
            /// Creates a new RxTabImageBased  folder.
            /// </summary>
            public RxTabImageBasedFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabImageBased", "?/?/tabpage[@controlname='RxTabImageBased']", parentFolder, 30000, null, false, "26e5a1bf-fc9d-4480-b23b-80b3ae79548a", "")
            {
                _monthcalendar1Info = new MonthCalendar1InfoClass(this);
                _chkshowimageInfo = new ChkShowImageInfoClass(this);
                _thecatInfo = new TheCatInfoClass(this);
                _rxtabimagebasedInfo = new RxTabImageBasedInfoClass(this);
            }

            /// <summary>
            /// The MonthCalendar1InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("63e59b41-d261-43fb-ae38-a51a8227229f")]
            public class MonthCalendar1InfoClass : RepoItemInfo
            {
                /// <summary>
                /// MonthCalendar1InfoClass class constructor.
                /// </summary>
                public MonthCalendar1InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "MonthCalendar1", "datetime[@controlname='monthCalendar1']", 30000, null, "63e59b41-d261-43fb-ae38-a51a8227229f")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("313074cc-92d0-4374-9da9-6a8bfa6f1959")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("313074cc-92d0-4374-9da9-6a8bfa6f1959");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("313074cc-92d0-4374-9da9-6a8bfa6f1959")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("313074cc-92d0-4374-9da9-6a8bfa6f1959", cropRect);
                }
            }

            /// <summary>
            /// The ChkShowImageInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("8bcaaf65-b416-441a-b107-4dda6f670d1f")]
            public class ChkShowImageInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ChkShowImageInfoClass class constructor.
                /// </summary>
                public ChkShowImageInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ChkShowImage", "checkbox[@controlname='chkShowImage']", 30000, null, "8bcaaf65-b416-441a-b107-4dda6f670d1f")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("3436ce34-c2fd-44a5-a009-e2ffbd1f1d17")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("3436ce34-c2fd-44a5-a009-e2ffbd1f1d17");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("3436ce34-c2fd-44a5-a009-e2ffbd1f1d17")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("3436ce34-c2fd-44a5-a009-e2ffbd1f1d17", cropRect);
                }
            }

            /// <summary>
            /// The TheCatInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("dc3c519b-73e0-4d00-843c-5df7d0df2ce0")]
            public class TheCatInfoClass : RepoItemInfo
            {
                /// <summary>
                /// TheCatInfoClass class constructor.
                /// </summary>
                public TheCatInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "TheCat", "picture[@controlname='TheCat']", 30000, null, "dc3c519b-73e0-4d00-843c-5df7d0df2ce0")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("7221e361-cbdd-4095-96ac-65e829aad589")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("7221e361-cbdd-4095-96ac-65e829aad589");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("7221e361-cbdd-4095-96ac-65e829aad589")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("7221e361-cbdd-4095-96ac-65e829aad589", cropRect);
                }
            }

            /// <summary>
            /// The RxTabImageBasedInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("4c69d799-7c1f-449c-95be-a65cca505b07")]
            public class RxTabImageBasedInfoClass : RepoItemInfo
            {
                /// <summary>
                /// RxTabImageBasedInfoClass class constructor.
                /// </summary>
                public RxTabImageBasedInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "RxTabImageBased", "", 30000, null, "4c69d799-7c1f-449c-95be-a65cca505b07")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("6428d0e3-6629-4a7c-99cf-93c9145aa956")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("6428d0e3-6629-4a7c-99cf-93c9145aa956");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("6428d0e3-6629-4a7c-99cf-93c9145aa956")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("6428d0e3-6629-4a7c-99cf-93c9145aa956", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("006e91bc-940e-47ce-b092-dc5caf88392a")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("006e91bc-940e-47ce-b092-dc5caf88392a");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("006e91bc-940e-47ce-b092-dc5caf88392a")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("006e91bc-940e-47ce-b092-dc5caf88392a", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("26e5a1bf-fc9d-4480-b23b-80b3ae79548a")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("26e5a1bf-fc9d-4480-b23b-80b3ae79548a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MonthCalendar1 item.
            /// </summary>
            [RepositoryItem("63e59b41-d261-43fb-ae38-a51a8227229f")]
            public virtual Ranorex.DateTime MonthCalendar1
            {
                get
                {
                    return _monthcalendar1Info.CreateAdapter<Ranorex.DateTime>(true);
                }
            }

            /// <summary>
            /// The MonthCalendar1 item info.
            /// </summary>
            [RepositoryItemInfo("63e59b41-d261-43fb-ae38-a51a8227229f")]
            public virtual MonthCalendar1InfoClass MonthCalendar1Info
            {
                get
                {
                    return _monthcalendar1Info;
                }
            }

            /// <summary>
            /// The ChkShowImage item.
            /// </summary>
            [RepositoryItem("8bcaaf65-b416-441a-b107-4dda6f670d1f")]
            public virtual Ranorex.CheckBox ChkShowImage
            {
                get
                {
                    return _chkshowimageInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkShowImage item info.
            /// </summary>
            [RepositoryItemInfo("8bcaaf65-b416-441a-b107-4dda6f670d1f")]
            public virtual ChkShowImageInfoClass ChkShowImageInfo
            {
                get
                {
                    return _chkshowimageInfo;
                }
            }

            /// <summary>
            /// The TheCat item.
            /// </summary>
            [RepositoryItem("dc3c519b-73e0-4d00-843c-5df7d0df2ce0")]
            public virtual Ranorex.Picture TheCat
            {
                get
                {
                    return _thecatInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The TheCat item info.
            /// </summary>
            [RepositoryItemInfo("dc3c519b-73e0-4d00-843c-5df7d0df2ce0")]
            public virtual TheCatInfoClass TheCatInfo
            {
                get
                {
                    return _thecatInfo;
                }
            }

            /// <summary>
            /// The RxTabImageBased item.
            /// </summary>
            [RepositoryItem("4c69d799-7c1f-449c-95be-a65cca505b07")]
            public virtual Ranorex.TabPage RxTabImageBased
            {
                get
                {
                    return _rxtabimagebasedInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The RxTabImageBased item info.
            /// </summary>
            [RepositoryItemInfo("4c69d799-7c1f-449c-95be-a65cca505b07")]
            public virtual RxTabImageBasedInfoClass RxTabImageBasedInfo
            {
                get
                {
                    return _rxtabimagebasedInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}