///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WebAppTest.Register
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RegisterUser recording.
    /// </summary>
    [TestModule("57b15426-becd-41c6-9738-041f65e2a6ed", ModuleType.Recording, 1)]
    public partial class RegisterUser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::WebAppTest.WebAppTestRepository repository.
        /// </summary>
        public static global::WebAppTest.WebAppTestRepository repo = global::WebAppTest.WebAppTestRepository.Instance;

        static RegisterUser instance = new RegisterUser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RegisterUser()
        {
            fname = "Shreyata";
            lname = "Sugandhi";
            phoneNumber = "1234567890";
            email = "shreyata@goldentouchsolutions.tech";
            address1 = "Silver Dale";
            address2 = "12345";
            city = "Pune";
            username = "shreyata";
            password = "shreyata1234";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RegisterUser Instance
        {
            get { return instance; }
        }

#region Variables

        string _fname;

        /// <summary>
        /// Gets or sets the value of variable fname.
        /// </summary>
        [TestVariable("43b15053-e5db-4085-9730-36965edc18e4")]
        public string fname
        {
            get { return _fname; }
            set { _fname = value; }
        }

        string _lname;

        /// <summary>
        /// Gets or sets the value of variable lname.
        /// </summary>
        [TestVariable("59abaf65-1f37-4f06-ac30-f2739ebfbe70")]
        public string lname
        {
            get { return _lname; }
            set { _lname = value; }
        }

        string _phoneNumber;

        /// <summary>
        /// Gets or sets the value of variable phoneNumber.
        /// </summary>
        [TestVariable("ae5f93fc-a458-4474-8dd5-9ced23e4d4f1")]
        public string phoneNumber
        {
            get { return _phoneNumber; }
            set { _phoneNumber = value; }
        }

        string _email;

        /// <summary>
        /// Gets or sets the value of variable email.
        /// </summary>
        [TestVariable("01e152b4-318f-46f3-88b5-533ec1f7b082")]
        public string email
        {
            get { return _email; }
            set { _email = value; }
        }

        string _address1;

        /// <summary>
        /// Gets or sets the value of variable address1.
        /// </summary>
        [TestVariable("6c70d1d8-bd78-4282-b70f-93fd61cddb71")]
        public string address1
        {
            get { return _address1; }
            set { _address1 = value; }
        }

        string _address2;

        /// <summary>
        /// Gets or sets the value of variable address2.
        /// </summary>
        [TestVariable("1b0b5f32-182e-472a-97a2-443f02f14f74")]
        public string address2
        {
            get { return _address2; }
            set { _address2 = value; }
        }

        string _city;

        /// <summary>
        /// Gets or sets the value of variable city.
        /// </summary>
        [TestVariable("baf1f7cc-cc64-4126-a98c-9255d28a1cf2")]
        public string city
        {
            get { return _city; }
            set { _city = value; }
        }

        string _username;

        /// <summary>
        /// Gets or sets the value of variable username.
        /// </summary>
        [TestVariable("39f75520-562e-487f-a999-9da8bc28e78a")]
        public string username
        {
            get { return _username; }
            set { _username = value; }
        }

        string _password;

        /// <summary>
        /// Gets or sets the value of variable password.
        /// </summary>
        [TestVariable("38289ae3-6257-477e-87cb-48bc4956f398")]
        public string password
        {
            get { return _password; }
            set { _password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.REGISTER' at 24;8.", repo.ApplicationUnderTest.SomeTableTag.REGISTERInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.SomeTableTag.REGISTER.Click("24;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.FirstName' at 65;11.", repo.ApplicationUnderTest.SomeTableTag.FirstNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.SomeTableTag.FirstName.Click("65;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$fname' with focus on 'ApplicationUnderTest.SomeTableTag.FirstName'.", repo.ApplicationUnderTest.SomeTableTag.FirstNameInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.SomeTableTag.FirstName.PressKeys(fname);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.LastName' at 65;10.", repo.ApplicationUnderTest.SomeTableTag.LastNameInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.SomeTableTag.LastName.Click("65;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$lname' with focus on 'ApplicationUnderTest.SomeTableTag.LastName'.", repo.ApplicationUnderTest.SomeTableTag.LastNameInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.SomeTableTag.LastName.PressKeys(lname);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.Phone' at 62;3.", repo.ApplicationUnderTest.SomeTableTag.PhoneInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.SomeTableTag.Phone.Click("62;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$phoneNumber' with focus on 'ApplicationUnderTest.SomeTableTag.Phone'.", repo.ApplicationUnderTest.SomeTableTag.PhoneInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.SomeTableTag.Phone.PressKeys(phoneNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UserName' at 42;12.", repo.ApplicationUnderTest.UserNameInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.UserName.Click("42;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$email' with focus on 'ApplicationUnderTest.UserName'.", repo.ApplicationUnderTest.UserNameInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.UserName.PressKeys(email);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.Address1' at 48;13.", repo.ApplicationUnderTest.SomeTableTag.Address1Info, new RecordItemIndex(9));
            repo.ApplicationUnderTest.SomeTableTag.Address1.Click("48;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$address1' with focus on 'ApplicationUnderTest.SomeTableTag.Address1'.", repo.ApplicationUnderTest.SomeTableTag.Address1Info, new RecordItemIndex(10));
            repo.ApplicationUnderTest.SomeTableTag.Address1.PressKeys(address1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.Address2' at 52;14.", repo.ApplicationUnderTest.SomeTableTag.Address2Info, new RecordItemIndex(11));
            repo.ApplicationUnderTest.SomeTableTag.Address2.Click("52;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$address2' with focus on 'ApplicationUnderTest.SomeTableTag.Address2'.", repo.ApplicationUnderTest.SomeTableTag.Address2Info, new RecordItemIndex(12));
            repo.ApplicationUnderTest.SomeTableTag.Address2.PressKeys(address2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.City' at Center.", repo.ApplicationUnderTest.SomeTableTag.CityInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.SomeTableTag.City.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$city' with focus on 'ApplicationUnderTest.SomeTableTag.Address2'.", repo.ApplicationUnderTest.SomeTableTag.Address2Info, new RecordItemIndex(14));
            repo.ApplicationUnderTest.SomeTableTag.Address2.PressKeys(city);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.State' at 59;11.", repo.ApplicationUnderTest.SomeTableTag.StateInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.SomeTableTag.State.Click("59;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'MH' with focus on 'ApplicationUnderTest.SomeTableTag.State'.", repo.ApplicationUnderTest.SomeTableTag.StateInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.SomeTableTag.State.PressKeys("MH");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.PostalCode' at 59;10.", repo.ApplicationUnderTest.SomeTableTag.PostalCodeInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.SomeTableTag.PostalCode.Click("59;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '411045' with focus on 'ApplicationUnderTest.SomeTableTag.PostalCode'.", repo.ApplicationUnderTest.SomeTableTag.PostalCodeInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.SomeTableTag.PostalCode.PressKeys("411045");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.Country' at 70;12.", repo.ApplicationUnderTest.SomeTableTag.CountryInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.SomeTableTag.Country.Click("70;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Selectbox.INDIA' at 106;10.", repo.Selectbox.INDIAInfo, new RecordItemIndex(20));
            repo.Selectbox.INDIA.Click("106;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.Country' at 321;11.", repo.ApplicationUnderTest.SomeTableTag.CountryInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.SomeTableTag.Country.Click("321;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Selectbox' at 323;386.", repo.Selectbox.SelfInfo, new RecordItemIndex(22));
            repo.Selectbox.Self.MoveTo("323;386");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Selectbox' at 317;189.", repo.Selectbox.SelfInfo, new RecordItemIndex(23));
            repo.Selectbox.Self.MoveTo("317;189");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Selectbox.INDIA' at 35;9.", repo.Selectbox.INDIAInfo, new RecordItemIndex(24));
            repo.Selectbox.INDIA.Click("35;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Email' at 49;4.", repo.ApplicationUnderTest.EmailInfo, new RecordItemIndex(25));
            repo.ApplicationUnderTest.Email.Click("49;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$username' with focus on 'ApplicationUnderTest.Email'.", repo.ApplicationUnderTest.EmailInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.Email.PressKeys(username);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'ApplicationUnderTest.Email'.", repo.ApplicationUnderTest.EmailInfo, new RecordItemIndex(27));
            repo.ApplicationUnderTest.Email.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$password'.", new RecordItemIndex(28));
            Keyboard.Press(password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.SomeTableTag.ConfirmPassword' at 69;10.", repo.ApplicationUnderTest.SomeTableTag.ConfirmPasswordInfo, new RecordItemIndex(29));
            repo.ApplicationUnderTest.SomeTableTag.ConfirmPassword.MoveTo("69;10");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$password' with focus on 'ApplicationUnderTest.SomeTableTag.ConfirmPassword'.", repo.ApplicationUnderTest.SomeTableTag.ConfirmPasswordInfo, new RecordItemIndex(30));
            repo.ApplicationUnderTest.SomeTableTag.ConfirmPassword.PressKeys(password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeTableTag.Register1' at 32;13.", repo.ApplicationUnderTest.SomeTableTag.Register1Info, new RecordItemIndex(31));
            repo.ApplicationUnderTest.SomeTableTag.Register1.Click("32;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=' Dear Shreyata Sugandhi,') on item 'ApplicationUnderTest.SomeTableTag.BTagDearShreyataSugandhi'.", repo.ApplicationUnderTest.SomeTableTag.BTagDearShreyataSugandhiInfo, new RecordItemIndex(32));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SomeTableTag.BTagDearShreyataSugandhiInfo, "InnerText", " Dear Shreyata Sugandhi,");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
